<%/***********************************************************
  *Copyright (C) 2015 Syntel and/or its affiliates
  *All rights reserved.
************************************************************/%>
<%
/********************************************************************
 Author 				: Syntel
 Version 				: 1.0
 Purpose				: This is for Application details List of SyntBotsITOps Application
 ********************************************************************/
%>
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Application Details</title>
<script>
/**
 *This is method is called during jsp is loaded
 */
$(document).ready(function() {
	fnIntlizApplicationDtlsDataTable();
	fnGetApplicationDtls();
})

/**
 *This function is used to get data table properties of application data table
 */
var varApplnDtlsDataTable;
function fnIntlizApplicationDtlsDataTable(){
	//alert("Inside Dtable")
	varApplnDtlsDataTable = $('#applicationDtlsDataTable').dataTable({
															"processing" : true,
															"destroy" : true,
															"scrollY" : "195px",
															"autoWidth" : true,
															"iDisplayLength" : 5,
															"sDom" : "<'dt-toolbar'<'col-xs-6 col-sm-6'f>r>"
																+ "t"
																+ "<'dt-toolbar-footer'<'col-sm-6 col-xs-6 hidden-xs'i><'col-sm-6 col-xs-12'p>>",
											"oTableTools" : {
															"aButtons" : [
																	"copy",
																	"csv",
																	"xls",
																	{
																		"sExtends" : "pdf",
																		"sTitle" : "SyntBots_PDF",
																		"sPdfMessage" : "SyntBots PDF Export",
																		"sPdfSize" : "letter"
																	},
																	{
																		"sExtends" : "print",
																		"sMessage" : "Generated by SyntBots <i>(press Esc to close)</i>"
																	} ],
															"sSwfPath" : "<%=request.getContextPath()%>/smartadmin/js/plugin/datatables/swf/copy_csv_xls_pdf.swf"
														}, 
														
														   "aoColumns" : [
														                  {
																"data" : "applnId"
															}, {
																"data" : "applnCode"
															},
															{
																"data" : "applnName"
															}, 
															{
																"data" : "applnDesc"
															},
															{
																"data" : "applnContextPath"
																
															},
															 {	
																"data" : "deleteFlag",
																"mRender": function (data, type, row) {
																	if( (typeof(data) !="undefined")  && (data != 'undefined') && (data != null) ){
																		if (data == '0') {
																			 return ' <span class="badge bg-color-green">No</span>';
																          } else if(data == '1') {
																        	   return ' <span class="badge bg-color-orange">Yes</span>';
																          }
																          else{
																		   return data;
																		  }
																		}else{
																		data = '';
																		return data;
																	}
																	  
														      }
															},
															{
																"data" : "applicationActions"
															},
															{
																"data" : "applnShortDesc"
															},
														    
															{
																"data" : "createdUser"
															},
															{
																"data" : "strCreatedDate"
															},
															{
																"data" : "modifiedUser"
															},{
																"data" : "strModifiedDate"
															}, 
															],
															"columnDefs": [
															               {
															                   "targets": [7,8,9,10,11],
															                   "visible": false,
															                   "searchable": false
															               }],
															               
	
	});
	}
	
/**
 *This method is used to intiate an ajax call to get application details list
 * @return success function/ error function
*/	
function fnGetApplicationDtls()
{
	  var getGetQueueDtlsJsonObj = {};
	  var strJSON = JSON.stringify(getGetQueueDtlsJsonObj);
	  fnCommonDoAjaxForGet("<%=request.getContextPath()%>/pages/getApplicationDtlsToView", strJSON,  "fnSucAfterGetApplicationDetails", "fnErrAfterGetApplicationDetails");
	
}
/**This method is called on success of fnCommonDoAjaxForGet util method with action get application details
* @param application details
*/
function fnSucAfterGetApplicationDetails(applicationdtls)
{
	fnLoadDataTable(varApplnDtlsDataTable, applicationdtls);
	varApplnDtlsDataTable.find('tbody tr:first').addClass('row_selected');
	fnGetApplicationDetailsPortion(applicationdtls.aaData[0]);
}
/**This method is called on failure of fnCommonDoAjaxForGet util method with action get application details
*/
function fnErrAfterGetApplicationDetails()
{
	alert("Application Details error");
}
/**This method is called on click of row in application details data table
*/
$("#applicationDtlsDataTable tbody").delegate("tr", "click", function() {
	var position = varApplnDtlsDataTable.fnGetPosition(this);
  	var aData = varApplnDtlsDataTable.fnGetData(position[0]);
  	fnGetApplicationDetailsPortion(aData[position]);
  	$("#applicationDtlsDataTable tbody tr").removeClass('row_selected');	
    $(this).addClass('row_selected');
  
});
/**This method is called to set values in application details portion 
* @param application details
*/
function fnGetApplicationDetailsPortion(varApplctnData){
	// alert("inside fnGetApplicationDetailsPortion():");
	 document.getElementById('applnName').innerHTML = varApplctnData.applnName;
	 document.getElementById('applnContextPath').innerHTML = varApplctnData.applnContextPath;
	 document.getElementById('createdUser').innerHTML = varApplctnData.createdUser;
	 document.getElementById('strCreatedDate').innerHTML = varApplctnData.strCreatedDate;
	 document.getElementById('modifiedUser').innerHTML = varApplctnData.modifiedUser;
	 document.getElementById('strModifiedDate').innerHTML = varApplctnData.strModifiedDate;
	 	  	
	}




function fnPopulateApplicationDtlsInPopUp(varApplicationId){

	//alert("varApplicationId:  " +varApplicationId);
	var allApplicationData = $('#applicationDtlsDataTable').DataTable().rows().data();
	for(var i=0;i<allApplicationData.length;i++)
	{
	var tempApplicationData = allApplicationData [i];
	//alert("inside fnPopulateApplicationDtlsInPopUp fn., tempApplicationData is:"+tempApplicationData +':tempApplicationData [applnId]:'+tempApplicationData ['applnId']+':');
	var tempApplicationId = tempApplicationData ['applnId'];
	//alert("appln name from tempApplicationData "+tempApplicationData.applnName);
	if(tempApplicationId == varApplicationId)
		{
	//alert('the Application is matched');
	
			 $("#applnId").val(tempApplicationId);
			 /* var applicatnName=tempApplicationData.applnName;
			 alert("applicatnName"+applicatnName); */
			$("#applnName").val(tempApplicationData['applnName']);
			$("#applnDesc").val(tempApplicationData['applnDesc']); 
			$("#applnContextPath").val(tempApplicationData['applnContextPath']);
			$("#applnCode").val(tempApplicationData['applnCode']);
			if(tempApplicationData['deleteFlag']==1){
				document.getElementById("checkbox").checked = true;
			}
			else{
			document.getElementById("checkbox").checked = false;
			}
			document.getElementById("deletecheckbox").style.display = 'block';
			$('#itopsAddeditPopUp').modal('show');
			document.getElementById("applnName").disabled = true; 
			
			break;
		}
    
}

}
/**This method is called on clicking of save button  in queue details data table To validate Qname
*/

function fnItOpsValApplicationDtls(){

var varApplicationID=getValuesFromInputField("applnId");
if(varApplicationID==0)
{
itOpsGetApplicationNameCount();
}
else{
fnItopsSaveApplicationDtls();
}
}
/**This method is called on clicking of save button  in queue details data table To get Qname
*/
function itOpsGetApplicationNameCount(){
	//alert("inside itOpsGetApplicationNameCount");
var varGetApplicationCountJsonObj = {};
varGetApplicationCountJsonObj['applnName'] = getValuesFromInputField("applnName");
var strJSON = JSON.stringify(varGetApplicationCountJsonObj);
//alert('strJSON is:'+strJSON+':');	
fnCommonDoAjaxForGet("<%=request.getContextPath()%>	/pages/itOpsValApplicationDtls",strJSON, "fnSucAfterGetApplicationNameCount","fnErrAfterGetApplicationNameCount");
	}
	/**This method is called on clicking on success of fnCommonDoAjaxForGet util method with action itOpsValQueDtls
	 * @param Queue details
	 */
	function fnSucAfterGetApplicationNameCount(data) {
		//alert("After success of fnSucAfterGetApplicationNameCount");
		//alert("data is" + data);
		if (data == 0) {
			fnItopsSaveApplicationDtls();
		} else {
			alert("Application Name Already  exists");
		}
	}
	/**This method is called on failure of fnCommonDoAjaxForGet util method with action itOpsValQueDtls
	 */
	function fnErrAfterGetApplicationNameCount() {
		alert("Failure");
	}
	/**This method is called on clicking of save button  in queue details data table To Save Quedetails
	 */
	function fnItopsSaveApplicationDtls() {

		//alert("inside fnItopsSaveApplicationDtls");
		var itopsSaveApplicationJsonObj = {};
		itopsSaveApplicationJsonObj['applnId'] = getValuesFromInputField("applnId");
		var checkboxvalue = document.getElementById("checkbox").checked;
		if (checkboxvalue == true) {
			itopsSaveApplicationJsonObj['deleteFlag'] = 1;
		} else {
			itopsSaveApplicationJsonObj['deleteFlag'] = 0;
		}
		itopsSaveApplicationJsonObj['applnName'] = getValuesFromInputField("applnName");
		//alert("appl name"+ itopsSaveApplicationJsonObj['applnName']);
		itopsSaveApplicationJsonObj['applnDesc'] = getValuesFromInputField("applnDesc");
		itopsSaveApplicationJsonObj['applnContextPath'] = getValuesFromInputField("applnContextPath");
		itopsSaveApplicationJsonObj['applnCode'] = getValuesFromInputField("applnCode");
		var strJSON = JSON.stringify(itopsSaveApplicationJsonObj);
		//alert('strJSON is ' + strJSON + ':');
		fnCommonDoAjaxForSave("<%=request.getContextPath()%>/pages/itopsAddEditApplicationDtls",strJSON,"fnItopsSaveApplicationDtlsAfterSaveAppln","fnItopsSaveApplicationDtlsErrAfterSaveAppln");

	}

	function fnItopsSaveApplicationDtlsAfterSaveAppln() {
		//alert("inside success ofitopsEditApplicationdtls ");
		$('#itopsAddeditPopUp').modal('hide');
		document.getElementById("deletecheckbox").style.display = 'block';
		fnGetApplicationDtls();
	}

	function fnItopsSaveApplicationDtlsErrAfterSaveAppln() {
		//alert("After Err server");
		$('#itopsErrorPopUp').modal('show');
	}
	function fnItopsSaveQueueclearData() {
		document.getElementById("applnId").value = "";
		document.getElementById("applnName").value = "";
		document.getElementById("applnDesc").value = "";
		document.getElementById("applnContextPath").value = "";
		document.getElementById("applnCode").value = "";

	}

	function fnItopsAddApplicationDtls() {
		//alert("inside fnItopsAddApplicationDtls ");

		$('#applnName').removeAttr('disabled');
		document.getElementById("applnId").value = "";
		document.getElementById("applnName").value = "";
		document.getElementById("applnDesc").value = "";
		document.getElementById("applnContextPath").value = "";
		document.getElementById("applnCode").value = "";
		document.getElementById("deletecheckbox").style.display = 'none';

		$('#itopsAddeditPopUp').modal('show');
	}
	function fnItopsClearForm() {
		$('#itopsErrorPopUp').hide;
		fnItopsSaveQueueclearData();
	}
</script>
</head>
<body>
			<!-- MAIN CONTENT -->
			<div id="content">
<div class="pull-right" style="padding-right: 2%;" >
				<a data-toggle="modal" onclick="fnItopsAddApplicationDtls()" class="btn btn-success txt-color-white pull-left  ">
					<i class="fa fa-circle-arrow-up fa-lg">
					</i>
					Add Application
				</a>   
				<br>
				<br>
			</div>
				<!-- widget grid -->
				<section id="widget-grid" class="">
				
					<!-- row -->
					<div class="row">
				
						<!-- NEW WIDGET START -->
						<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
				
							<!-- Widget ID (each widget will need unique ID)-->
							<div class="jarviswidget jarviswidget-color-darken" id="wid-id-0" data-widget-editbutton="false">
								
								<header>
								
									<h2>Application Details List </h2>
				
								</header>
				
								<!-- widget div-->
								<div>
				
									<!-- widget edit box -->
									<div class="jarviswidget-editbox">
										<!-- This area used as dropdown edit box -->
				
									</div>
									<!-- end widget edit box -->
				
									<!-- widget content -->
									<div class="widget-body no-padding">
				
										<table id="applicationDtlsDataTable" class="table table-striped table-bordered table-hover" width="100%">
											<thead>
											<tr>
									<th>Application ID</th>
									<th>Application Code</th>
									<th>Application Name</th>
									<th>Application Desc</th>
									 <th  style="width:15%;">Application ContextPath</th>
									<th>Deleted ?</th>
									<th>Actions</th>
									
										</tr>
											</thead>
											<tbody>
								
											</tbody>
									</table>

									</div>
									<!-- end widget content -->
				
								</div>
								<!-- end widget div -->
				
							</div>
							<!-- end widget -->
							</article>
							
							<!-- NEW WIDGET START -->
			<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
				<!-- Widget ID (each widget will need unique ID)-->
							
							<div class="jarviswidget jarviswidget-color-blueDark" id="wid-id-2" data-widget-editbutton="false">
								
								<header>
								<!-- 	<span class="widget-icon"> <i class="fa fa-table"></i> </span> -->
									<h2>Application Details </h2>
								</header>
								<!-- widget div-->
								<div>
									<!-- widget edit box -->
									<div class="jarviswidget-editbox">
										<!-- This area used as dropdown edit box -->
									</div>
									<!-- end widget edit box -->
									<!-- widget content -->
									<div class="widget-body no-padding">
										<div class="table-responsive">
											<table class="table table-hover"  width="100%">
												<tbody>
												<tr>
													<!-- <th>Application Name</th>
														<td id=applnName></td>
													</tr> -->
													<!-- <tr>
													<th>Application ContextPath</th>
														<td id=applnContextPath></td>
													</tr> -->
													<tr>
														<th>Created User</th>
														<td id='createdUser'></td>
													</tr>
													<tr>
														<th>Created Date</th>
														<td id='strCreatedDate'></td>
													</tr>
													<tr>
														<th>Modified User</th>
														<td id='modifiedUser'></td>
													</tr>
												    <tr>
														<th>Modified Date</th>
														<td id='strModifiedDate'></td>
													</tr>
													<!-- <tr>
														<th>Deleted</th>
														<td id='deleteFalg'></td>
													</tr> -->
													
												</tbody> 
											</table>
										</div>
										<!--  <div id='div1'> </div>  -->
									</div>
									<!-- end widget content -->

								</div>
								<!-- end widget div -->

							</div>
							<!-- end widget -->

				</article>
						<!-- WIDGET END -->
						

							</div></section></div>
							
							<div class="row">
		<div class="modal fade" id="itopsAddeditPopUp" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
						<h4 class="modal-title">
							<b> Application Details</b>
						</h4>
					</div>
					<input type="hidden" name="applnId" id="applnId" class="form-control"/>
					
					<div class="modal-body">
						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									<label for="category"></label> Application Name <input type="text"
										name="applnName" id="applnName"  class="form-control" disabled/>
										<span id="editApplnname"></span>
								</div>
							</div>
							
							<div class="col-md-6">
								<div class="form-group">
									<label for="category"></label> Application Description <input type="text"
										name="applnDesc" id="applnDesc" class="form-control"  required />
								</div>
							</div>
							
						</div>
						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									<label for="category"></label> Application ContextPath <input type="text"
										name="applnContextPath" id="applnContextPath" class="form-control"  required />
								</div>
							</div>
							
						   <div class="col-md-6">
								<div class="form-group">
									<label for="category"></label> Application Code <input type="text"
										name="applnContextPath" id="applnCode" class="form-control"  required />
								</div>
							</div>
							
						</div>
						 <div class="row" >
						<div class="col-md-6"  id="deletecheckbox" style="display:none">
							<div class="inline-group" >
									<label class="checkbox">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
									<input type="checkbox" id="checkbox" name="checkbox-inline" >
									<i></i>Deleted ?</label>
									</div>
							</div>
                            </div>
						<div class="modal-footer">
							<footer>
							
								<button type="button" id="save"class="btn btn-primary" onclick="javascript:fnItOpsValApplicationDtls();">Save</button>
								<button type="button" class="btn btn-default" data-dismiss="modal" onclick="javascript:fnItopsClearForm();">Cancel</button>
							</footer>
						</div>
							<!-- </form>	 -->
						</div>
					<!-- -/.modal-body -->
				</div>
				<!-- /.modal-content -->
			</div>
			<!-- /.modal-dialog -->

		</div>
			
	
				
</body>
</html>