<%/***********************************************************
  *Copyright (C) 2015 Syntel and/or its affiliates
  *All rights reserved.
************************************************************/%>
<%
/********************************************************************
 Author 				: Syntel
 Version 				: 1.0
 Purpose				: This is for ListIncidentDetails of SyntBotsITOps Application
 ********************************************************************/
%>

<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title> List Incident Details</title>
<% 
String strIncdntDtlsId= "";
if( request.getParameter("incdntDtlsId") != null){
	
	strIncdntDtlsId = request.getParameter("incdntDtlsId");
	//alert("incident dtls"+strIncdntDtlsId);
	System.out.println("strIncdntDtlsId is not null"+strIncdntDtlsId);
}

%>

<script type="text/javascript">
$(document).ready(function() {
	var varIncidentIdFromSopDtls=document.getElementById('incdntId').innerHTML;
	fnIntlizIncidentExecListDataTable();
	fnGetIncidentDetailsByIdToView();
	
	if(varIncidentIdFromSopDtls.length > 0){
		document.getElementById('incdntId').innerHTML =varIncidentIdFromSopDtls;
		fnItOpsGetIncidentExecDtlsByIncidentId();
	}
	else{
		fnItopsGetIncidentExecList(); 
	}	
});
function fnIntlizIncidentExecListDataTable(){
	
	itopsIncidentExecListDataTable = $('#itopsIncidentExecList').dataTable({
					"destroy" : true,
					"processing" : true,
					"scrollY" : "300px",
					"autoWidth" : true,
					"iDisplayLength" : 50,
					"sDom" : "<'dt-toolbar'<'col-xs-6 col-sm-6'f>r>"
							+ "t"
							+ "<'dt-toolbar-footer'<'col-sm-6 col-xs-6 hidden-xs'i><'col-sm-6 col-xs-12'p>>",

					"oTableTools" : {
						"aButtons" : [
								"copy",
								"csv",
								"xls",
								{
									"sExtends" : "pdf",
									"sTitle" : "SyntBots_PDF",
									"sPdfMessage" : "SyntBots PDF Export",
									"sPdfSize" : "letter"
								},
								{
									"sExtends" : "print",
									"sMessage" : "Generated by SyntBots <i>(press Esc to close)</i>"
								} ],
						"sSwfPath" : "<%=request.getContextPath()%>/smartadmin/js/plugin/datatables/swf/copy_csv_xls_pdf.swf"
					},

					//"sAjaxSource": 'getIncidentExecutionList',
					"aoColumns" : [ {
						"data" : "incidentExecId"
					},{
						"data" : "incidentExecStatus"
					},{
						"data" : "usrName"
					},
					{
						"data" : "applnName"
					},{
						"data" : "queName"
					},{
						"data" : "sopName"
					},{
						"data" : "wrkflwName"
					},{
						"data" : "strIncidentExecStartDate"
					},{
						"data" : "strIncidentExecEndDate"
					},{
						"data" : "incidentExecRemarks"
					},
					 {
						"data" : "incidentExecExcpMsg"
					},{
						"data" : "incidentExecExcpDtls"
					},{
						"data" : "incidentExecExcpStcktrce"
					}, 
					{
						"data" : "incidentExecParamDtlsList"
					}
				],
				"columnDefs": [
						            {
						                "targets": [4,5,6,7,8,9,10,11,12,13],
						                "visible": false,
						                "searchable": false
						            }
						       ]
					
				});
	
	

	
}


var varSopName = '';

function fnGetIncidentDetailsByIdToView() {
	//alert("inside getIncidentDetailsById ");
	var getIncidentByIdJsonObj = {};
	getIncidentByIdJsonObj['incdntDtlsId'] = <%=strIncdntDtlsId%>;
	var strJSON = JSON.stringify(getIncidentByIdJsonObj);
	//alert("strJson is"+strJSON);
	fnCommonDoAjaxForGet("<%=request.getContextPath()%>/pages/listIncidentDetailsById", strJSON,  "fnSucAfterGetIncidentDetails", "fnErrAfterGetIncidentDetails");

}


function fnSucAfterGetIncidentDetails(data)
{
	//alert("incdntId "+data);
	document.getElementById('incdntId').innerHTML = data.incdntId;
	//alert("incdntId "+data.incdntId);
	document.getElementById('incdntAssgnmntGrp').innerHTML = data.incdntAssgnmntGrp;
	 document.getElementById('incidentOriginalSeverity').innerHTML = data.incidentOriginalSeverity;
	document.getElementById('incdntAppName').innerHTML = data.incdntAppName;
	document.getElementById('incdntSrtDsc').innerHTML = data.incdntSrtDsc;
	document.getElementById('incdntDesc').innerHTML = data.incdntDesc;
	document.getElementById('incidentOpenedDate').innerHTML = data.strIncidentOpenedDate;
	document.getElementById('incdntState').innerHTML = data.incdntState;
	document.getElementById('incdntAssgndTo').innerHTML = data.incdntAssgndTo;
	fnItOpsGetIncidentExecDtlsByIncidentId();
	
	}
function fnErrAfterGetIncidentDetails() {
	alert("Inside fnErrAfterGetIncidentDetails");
  }

function fnItOpsGetIncidentExecDtlsByIncidentId(){

	var incidentId=document.getElementById('incdntId').innerHTML;
	//alert("incidentId"+incidentId);
    var getIncidentExecDtlsByIncidentIdJsonObj = {};
	getIncidentExecDtlsByIncidentIdJsonObj['incidentId'] =incidentId;
	var strJSON = JSON.stringify(getIncidentExecDtlsByIncidentIdJsonObj);
	//alert("strjson"+strJSON);
	fnCommonDoAjaxForGet("<%=request.getContextPath()%>/pages/getIncidentExecDtlsByIncidentId", strJSON,  "fnItopsLoadIncidentByIncidentExecIdDataTable", "fnErrAfterfnGetIncidentDtlsByIncidentExecId"); 
}

function fnItopsLoadIncidentByIncidentExecIdDataTable(varIncidentExecByIncidentIdTableData)
{
	
	//alert("inside  of the fnItopsLoadIncidentByIncidentExecIdDataTable fn::##########"+varIncidentExecByIncidentIdTableData+"######");
	document.getElementById('applnName').innerHTML =  '';
  	document.getElementById('queName').innerHTML = '';
  	document.getElementById('sopName').innerHTML = '';
  	document.getElementById('wrkflwName').innerHTML =  '';
	document.getElementById('incidentExecStartDate').innerHTML = '';
	document.getElementById('incidentExecEndDate').innerHTML = '';
	document.getElementById('incidentExecRemarks').innerHTML = '';
	document.getElementById('incidentExecExcpMsg').innerHTML ='';
	document.getElementById('incidentExecExcpDtls').innerHTML = '';
	document.getElementById('incidentExecExcpStcktrce').innerHTML = '';  
	fnLoadDataTable(itopsIncidentExecListDataTable, varIncidentExecByIncidentIdTableData);
	itopsIncidentExecListDataTable.find('tbody tr:first').addClass('row_selected');
 if( (typeof(varIncidentExecByIncidentIdTableData) !="undefined")  && (varIncidentExecByIncidentIdTableData != 'undefined') && (varIncidentExecByIncidentIdTableData != null)   
			 && (typeof(varIncidentExecByIncidentIdTableData.aaData) !="undefined")  && (varIncidentExecByIncidentIdTableData.aaData != 'undefined') && (varIncidentExecByIncidentIdTableData.aaData != null) && (varIncidentExecByIncidentIdTableData.aaData.length > 0)
			 && (typeof(varIncidentExecByIncidentIdTableData.aaData[0]) !="undefined")  && (varIncidentExecByIncidentIdTableData.aaData[0] != 'undefined') && (varIncidentExecByIncidentIdTableData.aaData[0] != null) 
		){
		fnSetSopExecutionRightPortion(varIncidentExecByIncidentIdTableData.aaData[0]);
	} 
	//alert("End  of the fnItopsLoadIncidentByIncidentExecIdDataTable fn::");
}
function fnErrAfterfnGetIncidentDtlsByIncidentExecId(){
	alert("Failure");
}

function fnItopsGetIncidentExecList()
{
	var getIncidentExecListJsonObj = {};	
	var strJSON = JSON.stringify(getIncidentExecListJsonObj);
	fnCommonDoAjaxForGet("<%=request.getContextPath()%>/pages/getIncidentExecutionList", strJSON,  "fnItopsLoadIncidentExecListDataTable", "fnItopsErrOnLoadIncidentExecListDataTable");
	
}

function fnItopsLoadIncidentExecListDataTable(varIncidentExecListTableData){
	//alert("inside fnAfterGetIncidentDetails "+varIncidentExecListTableData.aaData[0]);
	 fnLoadDataTable(itopsIncidentExecListDataTable, varIncidentExecListTableData);
	 itopsIncidentExecListDataTable.find('tbody tr:first').addClass('row_selected');
	 if( (typeof(varIncidentExecListTableData) !="undefined")  && (varIncidentExecListTableData != 'undefined') && (varIncidentExecListTableData != null)   
			 && (typeof(varIncidentExecListTableData.aaData) !="undefined")  && (varIncidentExecListTableData.aaData != 'undefined') && (varIncidentExecListTableData.aaData != null) && (varIncidentExecListTableData.aaData.length > 0)
			 && (typeof(varIncidentExecListTableData.aaData[0]) !="undefined")  && (varIncidentExecListTableData.aaData[0] != 'undefined') && (varIncidentExecListTableData.aaData[0] != null) 
		){
		fnSetSopExecutionRightPortion(varIncidentExecListTableData.aaData[0]);
	}
	// alert("End  of the fnItopsLoadIncidentExecListDataTable fn::");
}
function fnItopsErrOnLoadIncidentExecListDataTable(){
	alert("End  of the fnItopsErrOnLoadIncidentExecListDataTable fn::");
}

$("#itopsIncidentExecList tbody").delegate("tr", "click", function() {
	//alert("inside row click");
	$("#itopsIncidentExecList tbody tr").removeClass('row_selected');	
    $(this).addClass('row_selected');
 		var position = itopsIncidentExecListDataTable.fnGetPosition(this);
 		var aData = itopsIncidentExecListDataTable.fnGetData(position[0]);
	  	fnSetSopExecutionRightPortion(aData[position]);
		
}); 


function fnSetSopExecutionRightPortion(varSopData){
	document.getElementById('applnName').innerHTML = varSopData.applnName;
  	document.getElementById('queName').innerHTML = varSopData.queName;
  	document.getElementById('sopName').innerHTML = varSopData.sopName;
  	document.getElementById('wrkflwName').innerHTML = varSopData.wrkflwName;
    document.getElementById('incidentExecStartDate').innerHTML = varSopData.strIncidentExecStartDate;
	document.getElementById('incidentExecEndDate').innerHTML = varSopData.strIncidentExecEndDate;
	document.getElementById('incidentExecRemarks').innerHTML = varSopData.incidentExecRemarks;
	document.getElementById('incidentExecExcpMsg').innerHTML = varSopData.incidentExecExcpMsg;
	document.getElementById('incidentExecExcpDtls').innerHTML = varSopData.incidentExecExcpDtls;
	document.getElementById('incidentExecExcpStcktrce').innerHTML = varSopData.incidentExecExcpStcktrce; 
	$('#div1').html('');
	var data = varSopData.incidentExecParamDtlsList;
	 var html = '<table class="table table-hover"><thead><tr></tr></thead><tbody>';
	for (var i = 0, len = data.length; i < len;++i) {
	    html += '<tr>';	
	        html += '<th>' + data[i].paramName + '</th>';
	        html += '<td>' + data[i].paramValue + '</td>';
	    html += '</tr>';
	}
	html += '</tbody><tfoot><tr></tr></tfoot></table>';

	$(html).appendTo('#div1'); 
}

</script>


<script type="text/javascript">

</script>

</head>
<body>
		
				
			
			<!-- MAIN CONTENT -->
			<div id="content">
			
				<div class="row"  id="rowId">
               
               
               		<article class="col-sm-12 col-md-12 col-lg-12">
				<!-- Widget ID (each widget will need unique ID)-->
							
							<div class="jarviswidget jarviswidget-color-blueDark" id="wid-id-2" data-widget-editbutton="false">
								
								<header>
								<!-- 	<span class="widget-icon"> <i class="fa fa-table"></i> </span> -->
									<h2>Incident Details</h2>
								</header>
								<!-- widget div-->
								<div>
									<!-- widget edit box -->
									<div class="jarviswidget-editbox">
										<!-- This area used as dropdown edit box -->
									</div>
									<!-- end widget edit box -->
									<!-- widget content -->
									<div class="widget-body no-padding">
										<div class="table-responsive">
											<table id="table2" class="table table-hover">
                                       
                                                <tbody>
                                               
                                                   <tr>
                                                        <th>Incident ID</th>
                                                        <td id='incdntId'></td>
                                                        <th>Assignment Group</th>
                                                        <td id='incdntAssgnmntGrp'></td>
                                                    </tr>
                                                    
                                                
                                                    <tr>
                                                        <th>Original Severity</th>
                                                        <td id='incidentOriginalSeverity'></td>
                                                        <th>Incident Application Name</th>
                                                        <td id='incdntAppName'></td>
                                                    </tr>
                                               
                                                    <tr>
                                                 
                                                  
                                                        <th>Short Description</th>
                                                        <td><textarea id="incdntSrtDsc" rows="4" cols="50" disabled="disabled">
                                                        </textarea></td>
                                                         
                                                       
                                                        <th>Description</th>
                                                          <td><textarea id="incdntDesc" rows="4" cols="50" disabled="disabled">
                                                        </textarea></td>
                                                        
                                                    </tr>
                                                   
                                                    
                                                    <tr>
                                                   
                                                         <th>Open Date</th>
                                                         <td id='incidentOpenedDate'></td>
                                                          <th>Assigned To</th>
                                                        <td id='incdntAssgndTo'></td>
                                                           
                                                       
                                                    </tr>
                                               
                                                    <tr>
                                                        <th>Incident State</th>
                                                        <td id='incdntState'></td>
                                                        <th>&nbsp;</th>
                                                        <td>&nbsp;</td>
                                                        <!-- <th>SOP Name</th>
                                                        <td id='sopName'></td> -->
                                                    </tr>
                                                   
                                                   
                                               <!-- 
                                                    <tr>
                                                         <th>Modified Date</th>
                                                        <td id='incdntmodifiedDate'></td>
                                                         <th>Created Date</th>
                                                        <td id='incdntcreatedDate'></td>
                                                    </tr> -->
                                                   
                                                   
                                                  
                                                    
                                                </tbody>
                                            </table>
										</div>
										<!--  <div id='div1'> </div>  -->
									</div>
									<!-- end widget content -->

								</div>
								<!-- end widget div -->

							</div>
							<!-- end widget -->

				</article><div class="row"  id="rowId">
				<!-- NEW WIDGET START -->
			<!-- NEW WIDGET START -->
			<article class="col-xs-12 col-sm-12 col-md-12 col-lg-6">
					<!-- Widget ID (each widget will need unique ID)-->
					<div class="jarviswidget jarviswidget-color-blueDark" id="wid-id-0" data-widget-editbutton="false" data-widget-colorbutton="false">
				
						<header>
						<!-- 	<span class="widget-icon"> <i class="fa fa-table"></i> </span> -->
							<h2>Incident Execution List<h2>
						</header>
						<!-- widget div-->
						<div>		
							<!-- widget edit box -->
							<div class="jarviswidget-editbox">
								<!-- This area used as dropdown edit box -->
							</div>
							<!-- end widget edit box -->
							<!-- widget content -->
							<div class="widget-body no-padding">
								<table id="itopsIncidentExecList"
										class="table table-striped table-bordered table-hover"
										width="100%">
										<thead>
											<tr>
												<th>Incident Execution Id</th>
												<th>Incident Id</th>
												<th>User</th>
												 <th>Execution Status</th>
										   </tr>
										</thead>
										<tbody>
		
										</tbody>
								</table>
							</div>
							<!-- end widget content -->
						</div>
						<!-- end widget div -->
					</div>
					<!--END WIDGET ID -->
			
			</article>
			<article class="col-sm-12 col-md-12 col-lg-6">
				<!-- Widget ID (each widget will need unique ID)-->
							
							<div class="jarviswidget jarviswidget-color-blueDark" id="wid-id-2" data-widget-editbutton="false">
								
								<header>
								<!-- 	<span class="widget-icon"> <i class="fa fa-table"></i> </span> -->
									<h2>Incident Execution Details </h2>
								</header>
								<!-- widget div-->
								<div>
									<!-- widget edit box -->
									<div class="jarviswidget-editbox">
										<!-- This area used as dropdown edit box -->
									</div>
									<!-- end widget edit box -->
									<!-- widget content -->
									<div class="widget-body no-padding">
										<div class="table-responsive">
											<table class="table table-hover">
												<tbody>
													<tr>
														<th>Application Name</th>
														<td id='applnName'></td>
													</tr>
													<tr>
														<th>Queue Name</th>
														<td id='queName'></td>
													</tr>
													<tr>
														<th>SOP Name</th>
														<td id='sopName'></td>
													</tr>
													<tr>
														<th>Work Flow Name</th>
														<td id='wrkflwName'></td>
													</tr>
												    <tr>
														<th>Incident Execution Start Date</th>
														<td id='incidentExecStartDate'></td>
													</tr>
													<tr>
														<th>Incident Execution End Date</th>
														<td id='incidentExecEndDate'></td>
													</tr>
													<tr>
														<th>Remarks</th>
														<td><textarea id='incidentExecRemarks' rows="2" cols="50" disabled="disabled"></textarea></td>
													</tr>
													<tr>
														<th>Exception Message</th>
														<td><textarea id='incidentExecExcpMsg' rows="1" cols="50" disabled="disabled"></textarea></td>
													</tr>
													<tr>
														<th>Exception Details</th>
														<td><textarea  id='incidentExecExcpDtls' rows="1" cols="50" disabled="disabled"></textarea></td>
													</tr>
													<tr>
														<th>Exception StackTrace</th>
														<td><textarea  id='incidentExecExcpStcktrce' rows="4" cols="50" disabled="disabled"></textarea></td>
													</tr> 
													<!-- <tr>
														<th>Param Details</th>
														<td><textarea  id='incidentExecParamDtlsList' rows="4" cols="50"></textarea></td>
													</tr>-->
												</tbody> 
											</table>
										</div>
										<!--  <div id='div1'> </div>  -->
									</div>
									<!-- end widget content -->

								</div>
								<!-- end widget div -->

							</div>
							<!-- end widget -->

				</article>
						<!-- WIDGET END -->
						
						
				<article class="col-xs-12 col-sm-12 col-md-12 col-lg-6 pull-right">
					<!-- Widget ID (each widget will need unique ID)-->
					<div class="jarviswidget jarviswidget-color-blueDark" id="wid-id-0" data-widget-editbutton="false" data-widget-colorbutton="false">
				
						<header>
						<!-- 	<span class="widget-icon"> <i class="fa fa-table"></i> </span> -->
							<h2>Execution Param List<h2>
						</header>
						<!-- widget div-->
						<div>		
							<!-- widget edit box -->
							<div class="jarviswidget-editbox">
								<!-- This area used as dropdown edit box -->
							</div>
							<!-- end widget edit box -->
							<!-- widget content -->
							<div class="widget-body no-padding">
									<div class="table-responsive">
										 <div id='div1'> 
										 </div> 
									</div>
							</div>
							<!-- end widget content -->
						</div>
						<!-- end widget div -->
					</div>
					<!--END WIDGET ID -->
			
			</article>
							</div>
				
	
<script>


$('#dialog_simple').dialog({
autoOpen : false,
width : 400,
resizable : false,
modal : true,
title: false,
buttons : [{
html : "Ok",
"class" : "btn btn-primary",
click : function() {

$(this).dialog("close");
fnIncidentList();
}
} /* , {
html : "Cancel",
"class" : "btn btn-default",
click : function() {
alert("cancel");
$(this).dialog("close");
} 
} */]
});

</script>


</body>
</html>