<%/***********************************************************
  *Copyright (C) 2015 Syntel and/or its affiliates
  *All rights reserved.
************************************************************/%>
<%
/********************************************************************
 Author 				: Syntel
 Version 				: 1.0
 Purpose				: This is for User Application Queue Link List of SyntBotsITOps Application
 ********************************************************************/
%>
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>User Details</title>
<script>
/**
 *This is method is called during jsp is loaded
 */
$(document).ready(function() {
	fnInitializeUsrDetailsDataTable();
	fnItOpsGetUsrDetails();
})
/**
 *This function is used to get data table properties of user application queue link data table
 */
var varUsrDataTable;
function fnInitializeUsrDetailsDataTable(){
	//alert("Inside Dtable")
	varUsrDataTable = $('#usrDtlsDataTableId').dataTable({
															"processing" : true,
															"scrollY" : "195px",
															"autoWidth" : true,
															"iDisplayLength" : 5,
															"sDom" : "<'dt-toolbar'<'col-xs-6 col-sm-6'f>r>"
																+ "t"
																+ "<'dt-toolbar-footer'<'col-sm-6 col-xs-6 hidden-xs'i><'col-sm-6 col-xs-12'p>>",
											"oTableTools" : {
															"aButtons" : [
																	"copy",
																	"csv",
																	"xls",
																	{
																		"sExtends" : "pdf",
																		"sTitle" : "SyntBots_PDF",
																		"sPdfMessage" : "SyntBots PDF Export",
																		"sPdfSize" : "letter"
																	},
																	{
																		"sExtends" : "print",
																		"sMessage" : "Generated by SyntBots <i>(press Esc to close)</i>"
																	} ],
															"sSwfPath" : "<%=request.getContextPath()%>/smartadmin/js/plugin/datatables/swf/copy_csv_xls_pdf.swf"
														}, 
														  // "sAjaxSource": 'usrDetailsList',
														   "aoColumns" : [ {
																"data" : "usrId"
															}, {
																"data" : "usrCode"
															},{
																"data" : "usrFirstName"
															},{
																"data" : "usrShortName"
															},{
																"data" : "usrEmployeeCode"
															},{
																"data" : "usrDeleteFlag",
																"mRender": function (data, type, row) {
																	if( (typeof(data) !="undefined")  && (data != 'undefined') && (data != null) ){
																		 if (data == '0') {
																			 return ' <span class="badge bg-color-green">No</span>';
																          } else if(data == '1') {
																        	   return ' <span class="badge bg-color-orange">Yes</span>';
																          }
															          		else{
																	   		return data;
																	  		}
																	 }else{
																			data = '';
																			return data;
																		}
																	  
																}
															},{
																"data" : "usrPhoneNumber"
															},{
																"data" : "usrTitle"
															},{
																"data" : "usrComments"
															},{
																"data" : "usrMobileNumber"
															},{
																"data" : "usrEmail"
															},{
																"data" : "usrCreatedBy"
															},{
																"data" : "usrModifiedBy"
															},{
																"data" : "strUsrCreatedDate"
															},{
																"data" : "strUsrModifiedDate"
															},
															
														 ],
														 "columnDefs": [
															               {
															                   "targets": [7,8,9,10,11,12,13,14],
															                   "visible": false,
															                   "searchable": false
															               }],
														});
	/*varUsrDataTable.fnSetColumnVis( 0, false );*/
	  
}

/**
 *This method is used to intiate an ajax call to get User Details list
 * @return success function/ error function
*/
function fnItOpsGetUsrDetails(){
	var varGetUsrDetailsJsonObj = {};
	var strJSON = JSON.stringify(varGetUsrDetailsJsonObj);
	fnCommonDoAjaxForGet("<%=request.getContextPath()%>/pages/usrdetailslist", strJSON,  "fnItOpsSucAfterGetUsrDetails", "fnItOpsErrAfterGetDetails");
	
}
/**This method is called on success of fnCommonDoAjaxForGet util method with action get User Details list
* @param Queue details
*/
function fnItOpsSucAfterGetUsrDetails(varUsrDtlsDataFrmController){
	fnLoadDataTable(varUsrDataTable, varUsrDtlsDataFrmController);
	varUsrDataTable.find('tbody tr:first').addClass('row_selected');
	fnItOpsGetUserAdditionalDetailsArticle(varUsrDtlsDataFrmController.aaData[0]);
}
/**This method is called on failure of fnCommonDoAjaxForGet util method with action get User Details list
*/
function fnItOpsErrAfterGetDetails()
{
	alert("User  Details error");
} 
/**This method is called on clicking of row in User Application Queue link Details data table
*/
$("#usrDtlsDataTableId tbody").on( "click","tr", function() {
	var position = varUsrDataTable.fnGetPosition(this);
	var aData = varUsrDataTable.fnGetData(position[0]);
  	fnItOpsGetUserAdditionalDetailsArticle(aData[position]);
  	$("#usrDtlsDataTableId tbody tr").removeClass('row_selected');
    $(this).addClass('row_selected');
	
});

function fnItOpsGetUserAdditionalDetailsArticle(varItOpsUserAddtnalData){
	 document.getElementById('iudTitle').innerHTML = varItOpsUserAddtnalData.usrTitle;
	 document.getElementById('iudUsrCommnts').innerHTML = varItOpsUserAddtnalData.usrComments;
	 document.getElementById('iudMblNumbr').innerHTML = varItOpsUserAddtnalData.usrMobileNumber;
	 document.getElementById('iudEmailId').innerHTML = varItOpsUserAddtnalData.usrEmail;
	 document.getElementById('iudCreatedBy').innerHTML = varItOpsUserAddtnalData.usrCreatedBy;
	 document.getElementById('iudCreatedDate').innerHTML = varItOpsUserAddtnalData.strUsrCreatedDate;
	 document.getElementById('iudModifiedBy').innerHTML = varItOpsUserAddtnalData.usrModifiedBy;
	 document.getElementById('iudModifiedDate').innerHTML = varItOpsUserAddtnalData.strUsrModifiedDate;
} 
</script>
</head>
<body>
<!-- MAIN CONTENT -->
	<div id="content">
		<!-- widget grid -->
		<section id="widget-grid" class="">
			<!-- row -->
			<div class="row">
				<!-- NEW WIDGET START -->
				<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
					<!-- Widget ID (each widget will need unique ID)-->
					<div class="jarviswidget jarviswidget-color-darken" id="wid-id-0" data-widget-editbutton="false">
						<!-- widget options:
						usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
								data-widget-colorbutton="false"
								data-widget-editbutton="false"
								data-widget-togglebutton="false"
								data-widget-deletebutton="false"
								data-widget-fullscreenbutton="false"
								data-widget-custombutton="false"
								data-widget-collapsed="true"
								data-widget-sortable="false"
						-->
							<header>
								<h2>User Details </h2>
							</header>
							<!-- widget div-->
							<div>
								<!-- widget content -->
								<div class="widget-body no-padding">
									<table id="usrDtlsDataTableId" class="table table-striped table-bordered table-hover" width="100%">
										<thead>
											<tr>
												<th>User Id</th>
												<th>User Code</th>
												<th>First Name</th>
												<th>Short Name</th>
												<th>Employee Code</th>
												<th>Deleted&nbsp;<i class="fa fa-question"></i></th>
												<th style="width:15%;">Phone Number</th>	
											</tr>
										</thead>
										<tbody>
										</tbody>
									</table>
								</div>
								<!-- end widget content -->
							</div>
							<!-- end widget div -->
						</div>
						<!-- end widget -->
					</article>
					<!-- NEW WIDGET END -->
					<!-- NEW WIDGET START -->
					<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
						<!-- Widget ID (each widget will need unique ID) -->
						<div class="jarviswidget jarviswidget-color-blueDark" id="wid-id-2" data-widget-editbutton="false">
							<header>
								<h2>User Additional Details </h2>
							</header>
							<!-- widget div -->
							<div>
								<!-- widget edit box -->
								<div class="jarviswidget-editbox">
									<!-- This area used as dropdown edit box -->
								</div>
								<!-- end widget edit box -->
								<!-- widget content -->
								<div class="widget-body no-padding">
									<div class="table-responsive">
										<table class="table table-hover"  width="100%">
											<tbody>
												<tr>
													<th>Title</th>
													<td id='iudTitle'></td>
												</tr>
												<tr>
													<th>User Comments</th>
													<td id='iudUsrCommnts'></td>
												</tr>
												<tr>
													<th>Mobile Number</th>
													<td id='iudMblNumbr'></td>
												</tr>
												<tr>
													<th>E-mail Id</th>
													<td id='iudEmailId'></td>
												</tr>
												<tr>
													<th>Created By</th>
													<td id='iudCreatedBy'></td>
												</tr>
												<tr>
													<th>Created Date</th>
													<td id='iudCreatedDate'></td>
												</tr>
												<tr>
													<th>Modified By</th>
													<td id='iudModifiedBy'></td>
												</tr>
											    <tr>
													<th>Modified Date</th>
													<td id='iudModifiedDate'></td>
												</tr>
											</tbody> 
										</table>
									</div>
									<!-- table-responsive end  -->
								</div>
								<!-- end widget content -->
							</div>
							<!-- end widget div -->
						</div>
						<!-- end widget -->
					</article>
					<!-- WIDGET END -->
				</div>
				<!-- end row -->
			</section>
			<!-- end widget grid -->
		</div>
		<!-- END MAIN CONTENT -->
</body>
</html>