<%/***********************************************************
  *Copyright (C) 2015 Syntel and/or its affiliates
  *All rights reserved.
************************************************************/%>
<%
/********************************************************************
 Author 				: Syntel
 Version 				: 1.0
 Purpose				: This is for User Application Queue Link List of SyntBotsITOps Application
 ********************************************************************/
%>
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>User Application Queue Link</title>
<script>
/**
 *This is method is called during jsp is loaded
 */
$(document).ready(function() {
	fnInitializeUsrAppQLinkkDataTable();
	fnGetUsrAppQLnkDetails();
})
/**
 *This function is used to get data table properties of user application queue link data table
 */
var varUsrAppQLinkDataTable;
function fnInitializeUsrAppQLinkkDataTable(){
	//alert("Inside Dtable")
	varUsrAppQLinkDataTable = $('#usrAppQLinkDataTableId').dataTable({
															"processing" : true,
															"scrollY" : "195px",
															"autoWidth" : true,
															"iDisplayLength" : 5,
															"sDom" : "<'dt-toolbar'<'col-xs-6 col-sm-6'f>r>"
																+ "t"
																+ "<'dt-toolbar-footer'<'col-sm-6 col-xs-6 hidden-xs'i><'col-sm-6 col-xs-12'p>>",
											"oTableTools" : {
															"aButtons" : [
																	"copy",
																	"csv",
																	"xls",
																	{
																		"sExtends" : "pdf",
																		"sTitle" : "SyntBots_PDF",
																		"sPdfMessage" : "SyntBots PDF Export",
																		"sPdfSize" : "letter"
																	},
																	{
																		"sExtends" : "print",
																		"sMessage" : "Generated by SyntBots <i>(press Esc to close)</i>"
																	} ],
															"sSwfPath" : "<%=request.getContextPath()%>/smartadmin/js/plugin/datatables/swf/copy_csv_xls_pdf.swf"
														}, 
														  // "sAjaxSource": 'usrAppQLinkDetails',
														   "aoColumns" : [ {
															     "data" : "usrAppQLinkId"
															},{
															     "data" : "usrAppQLinkUsrId"
															},{
																"data" : "usrAppQLinkApplicationId"
															},{
																"data" : "usrAppQLinkQueueId"
															},{
																"data" : "strUsrAppQLinkUsrName"
															},{
																"data" : "strUsrAppQLinkApplicationName"
															},{
																"data" : "strUsrAppQLinkQueueName"
															}, {
																"data" : "usrAppQLinkToViewFlag",
																"mRender": function (data, type, row) {
																	if (data == '0') {
																		 return 'No';
															        }
																	if (data == '1') {
																		 return 'Yes';
															        }
																}
															},{
																"data" : "usrAppQLinkToExecuteFlag",
																"mRender": function (data, type, row) {
																	if (data == '0') {
																		 return 'No';
															        }
																	if (data == '1') {
																		 return 'Yes';
															        }
																}
															},{
																"data" : "usrAppQLinkDeleteFlag",
																"mRender": function (data, type, row) {
																	if( (typeof(data) !="undefined")  && (data != 'undefined') && (data != null) ){
																		 if (data == '0') {
																			 return ' <span class="badge bg-color-green">No</span>';
																          } else if(data == '1') {
																        	   return ' <span class="badge bg-color-orange">Yes</span>';
																          }
															          		else{
																	   		return data;
																	  		}
																	 }else{
																			data = '';
																			return data;
																		}
																	  
																}
															},
															{
																"data" : "strUsrAppQLinkCreatedByShortUserName"
															},
															{
																"data" : "strUsrAppQLinkModifiedByShortUserName"
															},
															{
																"data" : "strUsrAppQLinkCreatedDate"
															},
															{
																"data" : "strUsrAppQLinkModifiedDate"
															},
															{
																"data" : "usrAppQLinkActions"
															} 
														 ]
														});
	varUsrAppQLinkDataTable.fnSetColumnVis( 1, false );
	varUsrAppQLinkDataTable.fnSetColumnVis( 2, false );
	varUsrAppQLinkDataTable.fnSetColumnVis( 3, false );	  
}

/**
 *This method is used to intiate an ajax call to get User Application Queue link Details list
 * @return success function/ error function
*/
function fnGetUsrAppQLnkDetails()
{
	  var getGetUsrAppQLnkDetailsJsonObj = {};
	  var strJSON = JSON.stringify(getGetUsrAppQLnkDetailsJsonObj);
	  fnCommonDoAjaxForGet("<%=request.getContextPath()%>/pages/usrAppQLinkDetails", strJSON,  "fnSucAfterGetUsrAppQLnkDetails", "fnErrAfterGetUsrAppQLnkDetails");
	
}
/**This method is called on success of fnCommonDoAjaxForGet util method with action get User Application Queue link Details list
* @param Queue details
*/
function fnSucAfterGetUsrAppQLnkDetails(UsrAppQLinkDtls)
{
	fnLoadDataTable(varUsrAppQLinkDataTable, UsrAppQLinkDtls);
	varUsrAppQLinkDataTable.find('tbody tr:first').addClass('row_selected');
}
/**This method is called on failure of fnCommonDoAjaxForGet util method with action get User Application Queue link Details list
*/
function fnErrAfterGetUsrAppQLnkDetails()
{
	alert("User Application Queue link Details error");
} 
/**This method is called on clicking of row in User Application Queue link Details data table
*/
$("#usrAppQLinkDataTableId tbody").on('click', 'tr', function() {
	
	$("#usrAppQLinkDataTableId tbody tr").removeClass('row_selected');	
    $(this).addClass('row_selected');
	
});
function fnItOpsUsrAppQueueLinkAdd(){
	$('#usrAppQLinkUsrNameSelectId option').remove();
	$('#usrAppQLinkApplnNameSelectId option').remove();
	$('#usrAppQLinkQueNameSelectId option').remove();
	fnItOpsGetUsrNmsList();
}
function fnItOpsGetUsrNmsList(){
	var varGetUsrDetailsJsonObj = {};
	var strJSON = JSON.stringify(varGetUsrDetailsJsonObj);
	fnCommonDoAjaxForGet("<%=request.getContextPath()%>/pages/usrdetailslist", strJSON,  "fnUsrAppQueLnkSuccGetUsersNmsList", "fnUsrAppQueLnkErrGetUsersNmsList");	
}
function fnUsrAppQueLnkSuccGetUsersNmsList(varUserDtlsToView){
	//alert("success"+varUserDtlsToView);
	var varUAQLUsrNamesListOptns = '';
	for ( var i = 0; i < varUserDtlsToView.aaData.length; i++) {
		 varUAQLUsrNamesListOptns += '<option value="' +varUserDtlsToView.aaData[i].usrId+ '">'+ varUserDtlsToView.aaData[i].usrShortName + '</option>';
	} 
	$('#usrAppQLinkUsrNameSelectId').append(varUAQLUsrNamesListOptns);
	fnItOpsUsrAppQueLnkGetAppNmsList();
}
function fnUsrAppQueLnkErrGetUsersNmsList(){
	alert("failure");
}
function fnItOpsUsrAppQueLnkGetAppNmsList()
{
	  var getAppNamesListJsonObj = {};
	  var strJSON = JSON.stringify(getAppNamesListJsonObj);
	  fnCommonDoAjaxForGet("<%=request.getContextPath()%>/pages/getApplicationDtlsToView", strJSON,  "fnUsrAppQueLnkSuccGetAppNmsList", "fnUsrAppQueLnkErrGetAppNmsList");
	
}
function fnUsrAppQueLnkSuccGetAppNmsList(varApplicationDtlsToView){
	//alert("success"+varApplicationDtlsToView);
	var varUAQLApplnNamesListOptns = '';
	for ( var i = 0; i < varApplicationDtlsToView.aaData.length; i++) {
		varUAQLApplnNamesListOptns += '<option value="' +varApplicationDtlsToView.aaData[i].applnId+ '">'+ varApplicationDtlsToView.aaData[i].applnName + '</option>';
	} 
	$('#usrAppQLinkApplnNameSelectId').append(varUAQLApplnNamesListOptns);
	fnItOpsUsrAppQueLnkQueNmsList();
}
function fnUsrAppQueLnkErrGetAppNmsList(){
	alert("failure");
}
function fnItOpsUsrAppQueLnkQueNmsList()
{
	  //alert("inside fnItOpsUsrAppQueLnkQueNmsList");
	  var getQueueNamesListJsonObj = {};
	  var strJSON = JSON.stringify(getQueueNamesListJsonObj);
	  fnCommonDoAjaxForGet("<%=request.getContextPath()%>/pages/getQueueDtls", strJSON,  "fnUsrAppQueLnkSuccGetQueNmsList", "fnUsrAppQueLnkErrGetQueNmsList");
}
function fnUsrAppQueLnkSuccGetQueNmsList(varQueueDtlsToView){
	//alert("success"+varQueueDtlsToView);
	varvarUAQLQueNamesListOptions = '';
	for ( var i = 0; i < varQueueDtlsToView.aaData.length; i++) {
		varvarUAQLQueNamesListOptions += '<option value="' +varQueueDtlsToView.aaData[i].queId + '">'+ varQueueDtlsToView.aaData[i].queName + '</option>';
	}
	$('#usrAppQLinkQueNameSelectId').append(varvarUAQLQueNamesListOptions);
	$('#itOpsUsrAppQueueLnkAddPopUp').modal('show');
}
function fnUsrAppQueLnkErrGetQueNmsList(){
	alert("failure");
}
function fnItOpsValUsrApplnQueLinkDtls(){
	//alert("inside fnItOpsValUsrApplnQueLinkDtls");
	var varValUsrAppQueLnkDtlsJsonObj = {};
	varValUsrAppQueLnkDtlsJsonObj['usrAppQLinkUsrId'] =document.getElementById("usrAppQLinkUsrNameSelectId").value;
	varValUsrAppQueLnkDtlsJsonObj['usrAppQLinkApplicationId'] =document.getElementById("usrAppQLinkApplnNameSelectId").value;
	varValUsrAppQueLnkDtlsJsonObj['usrAppQLinkQueueId'] =document.getElementById("usrAppQLinkQueNameSelectId").value;
	var strJSON = JSON.stringify(varValUsrAppQueLnkDtlsJsonObj);
	//alert('strJSON is:'+strJSON+':');	
	fnCommonDoAjaxForGet("<%=request.getContextPath()%>/pages/valUsrApplnQueLinkDtls", strJSON,  "fnItOpsSuccValUsrApplnQueLinkDtls", "fnItOpsErrValUsrApplnQueLinkDtls"); 
}
function fnItOpsSuccValUsrApplnQueLinkDtls(varCountUsrApplnQueLink){
	//alert("success"+varCountUsrApplnQueLink);
	if(varCountUsrApplnQueLink==0){
		fnItOpsAddUsrApplnQueLinkDtls();
	}
	else{
		alert("User Application Queue Link already exists");
	} 
}
function fnItOpsErrValUsrApplnQueLinkDtls(){
	alert("failure");
}
function fnItOpsAddUsrApplnQueLinkDtls(){
	var varAddUsrApplnQueLnkJsonObj = {};
	
	varAddUsrApplnQueLnkJsonObj['usrAppQLinkUsrId'] =document.getElementById("usrAppQLinkUsrNameSelectId").value;
	varAddUsrApplnQueLnkJsonObj['usrAppQLinkApplicationId'] =document.getElementById("usrAppQLinkApplnNameSelectId").value;
	varAddUsrApplnQueLnkJsonObj['usrAppQLinkQueueId'] =document.getElementById("usrAppQLinkQueNameSelectId").value;
    var UAQLAddToViewChckBox=document.getElementById("usrAppQLinkAddToViewChckBox").checked;
    //alert("UAQLAddToViewChckBox"+UAQLAddToViewChckBox);
	if(UAQLAddToViewChckBox==true){
		varAddUsrApplnQueLnkJsonObj['usrAppQLinkToViewFlag'] = 1;
	}
	else{
		varAddUsrApplnQueLnkJsonObj['usrAppQLinkToViewFlag'] = 0;
	}
	
	var UAQLAddToExeChckBox=document.getElementById("usrAppQLinkAddToExeChckBox").checked;
    //alert("UAQLAddToExeChckBox"+UAQLAddToExeChckBox);
	if(UAQLAddToExeChckBox==true){
		varAddUsrApplnQueLnkJsonObj['usrAppQLinkToExecuteFlag'] = 1;
	}
	else{
		varAddUsrApplnQueLnkJsonObj['usrAppQLinkToExecuteFlag'] = 0;
	}
	//alert("values"+varAddUsrApplnQueLnkJsonObj['usrAppQLinkUsrId']+varAddUsrApplnQueLnkJsonObj['usrAppQLinkApplicationId']+varAddUsrApplnQueLnkJsonObj['usrAppQLinkQueueId']+varAddUsrApplnQueLnkJsonObj['usrAppQLinkToViewFlag']+varAddUsrApplnQueLnkJsonObj['usrAppQLinkToExecuteFlag']);
	var strJSON = JSON.stringify(varAddUsrApplnQueLnkJsonObj);
	//alert('strJSON is:'+strJSON+':');	
	if (confirm("Are you sure you want to Add details") == true) {
	fnCommonDoAjaxForSave("<%=request.getContextPath()%>/pages/addUsrApplnQueLinkDtls", strJSON,  "fnSuccAddUsrApplnQueLinkDtls", "fnErrAddUsrApplnQueLinkDtls"); 
	}
	else{
		$('#itOpsUsrAppQueueLnkAddPopUp').modal('hide');
	}
}
function fnSuccAddUsrApplnQueLinkDtls(){
	//alert("success");
	$('#itOpsUsrAppQueueLnkAddPopUp').modal('hide');
	fnGetUsrAppQLnkDetails();
	
}
function fnErrAddUsrApplnQueLinkDtls(){
	alert("failure");
}
function fnPopulateUsrApplnQLnkDtlsInPopUp(varUsrAppQLnkIdCon){
	//alert("inside fnPopulateUsrApplnQLnkDtlsInPopUp"+varUsrAppQLnkIdCon);
	$("#usrAppQLinkIdEditPopUp").val(varUsrAppQLnkIdCon);
	//alert("usrAppQLinkIdEditPopUp:  " +getValuesFromInputField("usrAppQLinkIdEditPopUp"));
	
	var allUsrApplnQLnkData = $('#usrAppQLinkDataTableId').DataTable().rows().data();
	for(var i=0;i<allUsrApplnQLnkData.length;i++)
	{
	var tempUsrApplnQLnkData = allUsrApplnQLnkData [i];
	//alert("inside fnPopulateUsrApplnQLnkDtlsInPopUp fn., tempUsrApplnQLnkData is:"+tempUsrApplnQLnkData +':tempUsrApplnQLnkData [usrAppQLinkId]:'+tempUsrApplnQLnkData ['usrAppQLinkId']);
	var tempUsrApplnQLnkId = tempUsrApplnQLnkData ['usrAppQLinkId'];
	if(tempUsrApplnQLnkId == varUsrAppQLnkIdCon)
		{
		    //alert(" in if tempUsrApplnQLnkId"+tempUsrApplnQLnkId)
			$("#usrAppQLinkUsrNameEditPopUp").val(tempUsrApplnQLnkData ['strUsrAppQLinkUsrName']);
			$("#usrAppQLinkAppNameEditPopUp").val(tempUsrApplnQLnkData ['strUsrAppQLinkApplicationName']);
			$("#usrAppQLinkQueueNameEditPopUp").val(tempUsrApplnQLnkData ['strUsrAppQLinkQueueName']);
			
			if(tempUsrApplnQLnkData ['usrAppQLinkToViewFlag']==1){
				document.getElementById("usrAppQLinkAddToViewEditChckBox").checked = true;
			}
			else{
			document.getElementById("usrAppQLinkAddToViewEditChckBox").checked = false;
			}
			
			if(tempUsrApplnQLnkData ['usrAppQLinkToExecuteFlag']==1){
				document.getElementById("usrAppQLinkAddToExeEditChckBox").checked = true;
			}
			else{
			document.getElementById("usrAppQLinkAddToExeEditChckBox").checked = false;
			}
			
			if(tempUsrApplnQLnkData ['usrAppQLinkDeleteFlag']==1){
				document.getElementById("usrAppQLinkEditDltChckBox").checked = true;
			}
			else{
			document.getElementById("usrAppQLinkEditDltChckBox").checked = false;
			}
			
			$('#itOpsUsrAppQueueLnkEditPopUp').modal('show');
			break;
		}
	
	} 
}
function fnUpdateUsrApplnQueLinkDtls(){
	var varUpdtUsrAppQLnkJsonObj = {};
	
	varUpdtUsrAppQLnkJsonObj['usrAppQLinkId'] = getValuesFromInputField("usrAppQLinkIdEditPopUp");
    var varUpdtUsrAppQLnkToView=document.getElementById("usrAppQLinkAddToViewEditChckBox").checked;
	if(varUpdtUsrAppQLnkToView==true){
		varUpdtUsrAppQLnkJsonObj['usrAppQLinkToViewFlag'] = 1;
	}
	else{
		varUpdtUsrAppQLnkJsonObj['usrAppQLinkToViewFlag'] = 0;
	}
	
    var varUpdtUsrAppQLnkToExec=document.getElementById("usrAppQLinkAddToExeEditChckBox").checked;
	if(varUpdtUsrAppQLnkToExec==true){
		varUpdtUsrAppQLnkJsonObj['usrAppQLinkToExecuteFlag'] = 1;
	}
	else{
		varUpdtUsrAppQLnkJsonObj['usrAppQLinkToExecuteFlag'] = 0;
	}
		
	var varUpdtUsrAppQLnkDelete=document.getElementById("usrAppQLinkEditDltChckBox").checked;
	if(varUpdtUsrAppQLnkDelete==true){
		varUpdtUsrAppQLnkJsonObj['usrAppQLinkDeleteFlag'] = 1;
	}
	else{
		varUpdtUsrAppQLnkJsonObj['usrAppQLinkDeleteFlag'] = 0;
	}
	
	var strJSON = JSON.stringify(varUpdtUsrAppQLnkJsonObj);
	//alert('strJSON is:'+strJSON+':');	
	if (confirm("Are you sure you want to edit details") == true) {
	fnCommonDoAjaxForSave("<%=request.getContextPath()%>/pages/updateUsrApplnQueLinkDtls", strJSON,  "fnSuccUpdateUsrApplnQueLinkDtls", "fnErrUpdateUsrApplnQueLinkDtls"); 
	}
	else{
		$('#itOpsUsrAppQueueLnkEditPopUp').modal('hide');
	}
}
function fnSuccUpdateUsrApplnQueLinkDtls(){
	//alert("success");
	$('#itOpsUsrAppQueueLnkEditPopUp').modal('hide');
	fnGetUsrAppQLnkDetails();
	
}
function fnErrUpdateUsrApplnQueLinkDtls(){
	alert("failure");
}
</script>
</head>
<body>
<!-- MAIN CONTENT -->
	<div id="content">
		<!-- widget grid -->
		<section id="widget-grid" class="">
			<!-- row -->
			<div class="row">
						   <!--START ROW -->
						   <div class="row">
								<!--BUTTONS START -->
								<div class="pull-right" style="padding-right: 2%;">
									<a data-toggle="modal" onclick="fnItOpsUsrAppQueueLinkAdd()" class="btn btn-success txt-color-white pull-right  ">
										<i class="fa fa-circle-arrow-up fa-lg"></i>Add 
									</a>   
								<br>
								<br>
							   </div>
							<!--BUTTONS END -->
						  </div>
						  <!--END ROW -->
				<!-- NEW WIDGET START -->
				<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
					<!-- Widget ID (each widget will need unique ID)-->
					<div class="jarviswidget jarviswidget-color-darken" id="wid-id-0" data-widget-editbutton="false">
						<!-- widget options:
						usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
								data-widget-colorbutton="false"
								data-widget-editbutton="false"
								data-widget-togglebutton="false"
								data-widget-deletebutton="false"
								data-widget-fullscreenbutton="false"
								data-widget-custombutton="false"
								data-widget-collapsed="true"
								data-widget-sortable="false"
						-->
							<header>
								<h2>User Application Queue Link </h2>
							</header>
							<!-- widget div-->
							<div>
								<!-- widget content -->
								<div class="widget-body no-padding">
									<table id="usrAppQLinkDataTableId" class="table table-striped table-bordered table-hover" width="100%">
										<thead>
											<tr>
												<th>Id</th>
												<th>User Id</th>
												<th>Application Id</th>
												<th>Queue Id</th>
												<th>User Name</th>
												<th>Application Name</th>
												<th>Queue Name</th>
												<th>To view</th>
												<th>To Execute</th>	
												<th>Deleted&nbsp;<i class="fa fa-question"></i></th>
												<th>Created By</th>	
												<th>Modified By</th>
												<th style="width:15%;">Created Date</th>	
												<th style="width:15%;">Modified Date</th>
												<th>Actions</th>
											</tr>
										</thead>
										<tbody>
										</tbody>
									</table>
								</div>
								<!-- end widget content -->
							</div>
							<!-- end widget div -->
						</div>
						<!-- end widget -->
					</article>
					<!-- NEW WIDGET END -->
				</div>
				<!-- end row -->
			</section>
			<!-- end widget grid -->
			
			<!-- Modal popup for  add  user application queue link -->
			<div class="modal fade" id="itOpsUsrAppQueueLnkAddPopUp" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
							<h4 class="modal-title">
								<b> Add User Application Queue Link</b>
							</h4>
						</div>
						<input type="hidden" id="usrAppQLinkIdAddPopUp" name="usrAppQLinkIdAddPopUp" class="form-control"/>
						<div class="modal-body">
						<div class="row">
							<div class="col-md-8">
								<div class="form-group">
									<label for="category"></label>User Name  <sup class="reqdField">*</sup><br>
									<select	style="width: 270px;" id="usrAppQLinkUsrNameSelectId"
										name="usrAppQLinkUsrNameSelectId">
									</select>
								</div>
							</div>
						</div>
						
						<div class="row">
							<div class="col-md-8">
								<div class="form-group">
									<label for="category"></label>Application Name  <sup class="reqdField">*</sup><br>
									<select style="width: 270px;" id="usrAppQLinkApplnNameSelectId"
										name="usrAppQLinkApplnNameSelectId">
									</select>
									
								</div>
							</div>
						</div>
			
						<div class="row">
							<div class="col-md-8">
								<div class="form-group">
									<label for="category"></label>Queue Name  <sup class="reqdField">*</sup><br> 
									 <select style="width: 270px;" id="usrAppQLinkQueNameSelectId"
										name="usrAppQLinkQueNameSelectId">
									</select>
								</div>
							</div>
						</div>
						
						<div class="row">
							<div class="col-md-6" >
								<div class="inline-group">
									<label class="checkbox">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
									<input type="checkbox" id="usrAppQLinkAddToViewChckBox" name="usrAppQLinkAddToViewChckBox">
									<i></i>To view ?</label>
									</div>
							</div>
							<div class="col-md-6" >
								<div class="inline-group">
									<label class="checkbox">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
									<input type="checkbox" id="usrAppQLinkAddToExeChckBox" name="usrAppQLinkAddToExeChckBox">
									<i></i>To execute ?</label>
									</div>
							</div>
                        </div>
						<div class="modal-footer">
							<footer>
							<!-- onclick="javascript:fnItopsAddNewApplnQueSoplinkDetails(); -->
								<button type="button" class="btn btn-primary" onclick="javascript:fnItOpsValUsrApplnQueLinkDtls();">Save</button>
								<button type="button" class="btn btn-default" data-dismiss="modal" onclick="javascript:fnItopsClearForm();">Cancel</button>
							</footer>
						</div>
						<!-- </form>	 -->
						</div>
						</div>
					<!-- -/.modal-body -->
				</div>
				<!-- /.modal-content -->
			</div>
			<!-- /.modal-dialog -->
			<!-- Modal popup end for add user application queue link -->
			
			
			<!-- Modal popup for  edit  user application queue link -->
			<div class="modal fade" id="itOpsUsrAppQueueLnkEditPopUp" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
							<h4 class="modal-title">
								<b> Edit User Application Queue Link</b>
							</h4>
						</div>
						<input type="hidden" id="usrAppQLinkIdEditPopUp" name="usrAppQLinkIdEditPopUp" class="form-control"/>
						<div class="modal-body">
						
						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									<label for="category"></label>User Name<input type="text"
										name="usrAppQLinkUsrNameEditPopUp" id="usrAppQLinkUsrNameEditPopUp"  class="form-control" disabled/>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									<label for="category"></label>Application Name<input type="text"
										name="usrAppQLinkAppNameEditPopUp" id="usrAppQLinkAppNameEditPopUp"  class="form-control" disabled/>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									<label for="category"></label>Queue Name<input type="text"
										name="usrAppQLinkQueueNameEditPopUp" id="usrAppQLinkQueueNameEditPopUp"  class="form-control" disabled/>
								</div>
							</div>
						</div>
						
						<div class="row">
							<div class="col-md-6" >
								<div class="inline-group">
									<label class="checkbox">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
									<input type="checkbox" id="usrAppQLinkAddToViewEditChckBox" name="usrAppQLinkAddToViewEditChckBox">
									<i></i>To view ?</label>
									</div>
							</div>
							<div class="col-md-6" >
								<div class="inline-group">
									<label class="checkbox">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
									<input type="checkbox" id="usrAppQLinkAddToExeEditChckBox" name="usrAppQLinkAddToExeEditChckBox">
									<i></i>To execute ?</label>
									</div>
							</div>
                        </div>
						<div class="row">
							<div class="col-md-6">
								<div class="inline-group">
									<label class="checkbox">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
									<input type="checkbox" id="usrAppQLinkEditDltChckBox" name="usrAppQLinkEditDltChckBox">
									<i></i>Delete ?</label>
									</div>
							</div>
                        </div>
			
						<div class="modal-footer">
							<footer>
							<!-- onclick="javascript:fnItopsAddNewApplnQueSoplinkDetails(); -->
								<button type="button" class="btn btn-primary" onclick="javascript:fnUpdateUsrApplnQueLinkDtls();">Save</button>
								<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
							</footer>
						</div>
						<!-- </form>	 -->
						</div>
						</div>
					<!-- -/.modal-body -->
				</div>
				<!-- /.modal-content -->
			</div>
			<!-- /.modal-dialog -->
			<!-- Modal popup end for add user application queue link -->
			
			
		</div>
		<!-- END MAIN CONTENT -->
</body>
</html>