<%/***********************************************************
  *Copyright (C) 2015 Syntel and/or its affiliates
  *All rights reserved.
************************************************************/%>
<%
/********************************************************************
 Author 				: Syntel
 Version 				: 1.0
 Purpose				: This is for workflow details of SyntBotsItOps Application
 ********************************************************************/
%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<title> Workflow Details</title>
<!-- <style>
tr.row_selected td{background-color:lightblue !important;}
</style> --> 			
<script type="text/javascript">
/**
 *This is method is called during jsp is loaded
 */
var itOpsVarWrkflwParamDataTable;
jQuery(document).ready(function() {
	fnIntlizItopsWrkflwParamDataTable();
	fnGetWrkflwDtls();
		
	// START AND FINISH DATE
	$('#wrkflwDcmsnDatePopUp').datepicker({
		dateFormat : 'yy-mm-dd',
		timeFormat:  'HH:mm',
		
		prevText : '<i class="fa fa-chevron-left"></i>',
		nextText : '<i class="fa fa-chevron-right"></i>',
	});
});
/**
 *This function is used to get data table properties of workflow param data table
 */
function fnIntlizItopsWrkflwParamDataTable(){
	//alert("Inside Workflow data table");
	itOpsVarWrkflwParamDataTable = $('#itOpsWrkflwParam').dataTable({
					"destroy" : true,
					"processing" : true,
					"scrollY" : "195px",
					"autoWidth" : true,
					"iDisplayLength" : 5,
					"sDom" : "<'dt-toolbar'<'col-xs-6 col-sm-6'f>r>"
							+ "t"
							+ "<'dt-toolbar-footer'<'col-sm-6 col-xs-6 hidden-xs'i><'col-sm-6 col-xs-12'p>>",

					"oTableTools" : {
						"aButtons" : [
								"copy",
								"csv",
								"xls",
								{
									"sExtends" : "pdf",
									"sTitle" : "SyntBots_PDF",
									"sPdfMessage" : "SyntBots PDF Export",
									"sPdfSize" : "letter"
								},
								{
									"sExtends" : "print",
									"sMessage" : "Generated by SyntBots <i>(press Esc to close)</i>"
								} ],
						"sSwfPath" : "<%=request.getContextPath()%>/smartadmin/js/plugin/datatables/swf/copy_csv_xls_pdf.swf"
					},

					
					"aoColumns" : [ {
						"data" : "wrkflwId"
					},{
						"data" : "paramName"
					},{
						"data" : "paramCode"
					},{
						"data" : "paramValidation"
					},{
						"data" : "paramOrder"
					},{
						"data" : "strParamMandatory"
					},{
						"data" : "paramDefaultValue"
					},{
						"data" : "strParamToBeStored"
					},{
						"data" : "strParamToBeEncrypted"
					},{
						"data" : "strParamToBeShown"
					},{
						"data" : "strParamValToBeShown"
					},{
						"data" : "paramTypeInWorkflow"
					}, {
						"data" : "strCreatedDateParam"
					},{
						"data" : "strModifiedDateParam"
					}, {
						"data" : "strConsiderSopParamDtl"
					},{
						"data" : "strDeleteFlag"
					}, {
						"data" : "createdByUsernameParam"
					},{
						"data" : "modifiedByUsernameParam"
					}, {
						"data" : "paramDesc"
					},{
						"data" : "paramType"
					},{
						"data" : "wrkflwParamAction"
					}],
					
					"columnDefs": [
						            {
						                "targets": [12,13,16,17,18],
						                "visible": false,
						                "searchable": false
						            }
						       ]
				});
	
}
/**
 *This method is used to intiate an ajax call to get workflow details list
 * @return success function/ error function
*/
function fnGetWrkflwDtls(){
	var getWrkflwDtlsJsonObj = {};	
	var strJSON = JSON.stringify(getWrkflwDtlsJsonObj);
	//alert('strJSON is:'+strJSON+':');		
	fnCommonDoAjaxForGet("<%=request.getContextPath()%>/pages/listWrkflowDtls", strJSON,  "fnSucLoadWrkflwDtlsSelect", "fnErrLoadWrkflwDtlsSelect");	
}
/**This method is called on success of fnCommonDoAjaxForGet util method with action get workflow details 
 * this method loads workflow detailswhich is selected in dropdown
 * @param application details
*/
function fnSucLoadWrkflwDtlsSelect(varWrkflwDtlsTableData){
	
	 $('#wrkflwNameSelectId option').remove();
	 var varWrkflwNamesListOptions ='';
	 for(var i=0; i<varWrkflwDtlsTableData.aaData.length;i++){
		 //alert("The workflow name"+varWrkflwDtlsTableData.aaData[i].wrkflwName );
		
		varWrkflwNamesListOptions += '<option value="' +varWrkflwDtlsTableData.aaData[i].wrkflwName + '">'+ varWrkflwDtlsTableData.aaData[i].wrkflwName + '</option>';
		//alert("++++++++++++++++++++++++++++++++"+varWrkflwNamesListOptions);
		 }
	 	$('#wrkflwNameSelectId').append(varWrkflwNamesListOptions);
		getWrkflwDtlsByName(varWrkflwDtlsTableData.aaData[0].wrkflwName);
}
/**This method is called on failure of fnCommonDoAjaxForGet util method with action get workflow details 
*/
function fnErrLoadWrkflwDtlsSelect(){
	alert("End of the fnErrLoadWrkflwDtlsDataTable fn::");
}
/**This method is called on clicking of row in workflow params data table
*/
/* $("#itOpsWrkflwParam tbody").delegate("tr", "click", function() {
	//alert("row click");	
	
	
	var position = itOpsVarWrkflwParamDataTable.fnGetPosition(this);
  	var aData = itOpsVarWrkflwParamDataTable.fnGetData(position[0]);
  	//alert(aData[position]['createdByUsernameParam']);
    fnSetWrkflwParamDtls(aData[position]);
}); */

$("#itOpsWrkflwParam tbody").on('click', 'tr', function() {
	//alert("row click");	
	var position = itOpsVarWrkflwParamDataTable.fnGetPosition(this);
  	var aData = itOpsVarWrkflwParamDataTable.fnGetData(position[0]);
  	//alert(aData[position]['createdByUsernameParam']);
    fnSetWrkflwParamDtls(aData[position]);
    
    $("#itOpsWrkflwParam tbody tr").removeClass('row_selected');	
    $(this).addClass('row_selected');
	
});



/**This method is called on to load workflow param values corresponding to row click 
*/
function fnSetWrkflwParamDtls(varData)
{
	
	//alert("inside paramdetails load"+varData['createdByUsernameParam']);
	//alert(varData['wrkflwParamAction']);
	document.getElementById('createdByUsernameParam').innerHTML = varData['createdByUsernameParam'];
	document.getElementById('modifiedByUsernameParam').innerHTML = varData['modifiedByUsernameParam'];
	document.getElementById('strCreatedDateParam').innerHTML = varData['strCreatedDateParam'];
	document.getElementById('strModifiedDate').innerHTML = varData['strModifiedDate'];
	document.getElementById('paramDesc').innerHTML = varData['paramDesc'];
}
/**This method is called to clear workflow param values
*/
function fnClearWrkflwParamDtls()
{
	//alert("inside paramdetails load"+varData['createdByUsernameParam']);
	document.getElementById('createdByUsernameParam').innerHTML = '';
	document.getElementById('modifiedByUsernameParam').innerHTML ='';
	document.getElementById('strCreatedDateParam').innerHTML ='';
	document.getElementById('strModifiedDate').innerHTML = '';
	document.getElementById('paramDesc').innerHTML ='';
}
/**This method is calledto load workflow param details data table with corresponding param values
 * @param workflow param values
*/
function fnSetWrkflwParamDtlsTable(varData)
{
	var wrkflwParamList=varData['workflowParamLnkList'];
	fnLoadDataTableFromList(itOpsVarWrkflwParamDataTable, wrkflwParamList);
	itOpsVarWrkflwParamDataTable.find('tbody tr:first').addClass('row_selected');
	fnClearWrkflwParamDtls();
	if((typeof(wrkflwParamList)!="undefined") && (wrkflwParamList != 'undefined') && (wrkflwParamList != null) && (wrkflwParamList.length > 0)){
		fnSetWrkflwParamDtls(wrkflwParamList[0]);
	}
	
	
	$("#wrkflwIdParamPopUp").val(varData['wrkflwId']);
}
/**
 *This method is used to intiate an ajax call to get workflow details based on workflow name selected in drop down
 * @param workflow name
 * @return success function/ error function
*/
function getWrkflwDtlsByName(varWrkflwName)
{
	//alert("View"+varWrkflwName+"Details");
	var varWrkflwName = document.getElementById("wrkflwNameSelectId").value;	
	var wrlflwJsonObj = {};		
	wrlflwJsonObj['wrkflwName'] = varWrkflwName;
	var strJSON = JSON.stringify(wrlflwJsonObj);
	fnCommonDoAjaxForGet("<%=request.getContextPath()%>/pages/getWrkflwDtlsByWrkflwName", strJSON,  "fnLoadWrkflwDtls", "fnErrOnLoadWrkflwDtls");		
	
}
/**This method is called on success of fnCommonDoAjaxForGet util method with action get workflow details
* This method loads workflow details on changing name in dropdown 
* @param application details
*/

function fnLoadWrkflwDtls(wrkflwDtls){
	
	document.getElementById('wrkflwId').innerHTML = wrkflwDtls['wrkflwId'];
	document.getElementById('wrkflwDesc').innerHTML = wrkflwDtls['wrkflwDesc'];
	document.getElementById('wrkflwUrl').innerHTML = wrkflwDtls['wrkflwUrl'];
	document.getElementById('wrkflwVersion').innerHTML = wrkflwDtls['wrkflwVersion'];
	document.getElementById('wrkflwDeploymentId').innerHTML = wrkflwDtls['wrkflwDeploymentId'];
	document.getElementById('strDecomisionDate').innerHTML = wrkflwDtls['strDecomisionDate'];
	document.getElementById('wrkflwListenQueue').innerHTML = wrkflwDtls['wrkflwListenQueue'];
	document.getElementById('strDeleteFlag').innerHTML = wrkflwDtls['strDeleteFlag'];
	document.getElementById('createdByUserName').innerHTML = wrkflwDtls['createdByUserName'];
	document.getElementById('modifiedByUserName').innerHTML = wrkflwDtls['modifiedByUserName'];
	document.getElementById('strCreatedDate').innerHTML = wrkflwDtls['strCreatedDate'];
	document.getElementById('strModifiedDate').innerHTML = wrkflwDtls['strModifiedDate'];
	//alert("wrkflwDtls['strModifiedDate']"+wrkflwDtls['strModifiedDate']);
	document.getElementById('wrkflwDefinitionId').innerHTML = wrkflwDtls['wrkflwDefinitionId'];
	document.getElementById('wrkflwUsername').innerHTML = wrkflwDtls['wrkflwUsername'];
	document.getElementById('wrkflwPassword').innerHTML = wrkflwDtls['wrkflwPassword'];
	fnSetWrkflwParamDtlsTable(wrkflwDtls);
}
/**This method is called on failure of fnCommonDoAjaxForGet util method with action get workflow details
*/
function fnErrOnLoadWrkflwDtls(){
	alert("Failure");
}
/**This method is called to load add workflow popup
 */
function fnItOpsWrkflwDtlsAddWrkflw() {
	document.getElementById("wrkflwIdPopUp").value = "";
 	document.getElementById("wrkflwNamePopUp").value = "";
 	document.getElementById('wrkflwNamePopUp').style.border = '';
	document.getElementById("wrkflwDescPopUp").value = "";
	document.getElementById("wrkflwURLPopUp").value = "";
	document.getElementById('wrkflwURLPopUp').style.border = '';
	document.getElementById("wrkflwVersionPopUp").value = "";
	document.getElementById("wrkflwdeplymntIdPopUp").value = "";
	document.getElementById("wrkflwdeplymntIdPopUp").style.border = '';
	document.getElementById("wrkflwDcmsnDatePopUp").value = "";
	document.getElementById("wrkflwLstnQueuePopUp").value = "";
	document.getElementById("wrkflwDefIdPopUp").value = "";
	document.getElementById('wrkflwDefIdPopUp').style.border = '';
	document.getElementById("wrkflwUsrnamePopUp").value = "";
	document.getElementById("wrkflwUsrnamePopUp").style.border = '';
	document.getElementById("wrkflwPwdPopUp").value = "";
	document.getElementById("wrkflwPwdPopUp").style.border = '';
	document.getElementById("itOpswrkflwDtlsDltDiv").style.display = 'none'; 
	$('#itOpsWrkflwDtlsAddEditPopUp').modal('show');
}
function fnItOpsWrkflwDtlsEditWrkflw(){
	//alert("inside edit");
	document.getElementById("wrkflwIdPopUp").value = document.getElementById('wrkflwId').innerHTML;
 	document.getElementById("wrkflwNamePopUp").value = getValuesFromInputField("wrkflwNameSelectId");
 	document.getElementById('wrkflwNamePopUp').style.border = '';
	document.getElementById("wrkflwDescPopUp").value = document.getElementById('wrkflwDesc').innerHTML;
	document.getElementById("wrkflwURLPopUp").value = document.getElementById('wrkflwUrl').innerHTML;
	document.getElementById('wrkflwURLPopUp').style.border = '';
	document.getElementById("wrkflwVersionPopUp").value = document.getElementById('wrkflwVersion').innerHTML;
	document.getElementById("wrkflwdeplymntIdPopUp").value = document.getElementById('wrkflwDeploymentId').innerHTML;
	document.getElementById("wrkflwdeplymntIdPopUp").style.border = '';
	document.getElementById("wrkflwDcmsnDatePopUp").value = document.getElementById('strDecomisionDate').innerHTML;
	document.getElementById("wrkflwLstnQueuePopUp").value = document.getElementById('wrkflwListenQueue').innerHTML;
	document.getElementById("wrkflwDefIdPopUp").value = document.getElementById('wrkflwDefinitionId').innerHTML;
	document.getElementById('wrkflwDefIdPopUp').style.border = '';
	document.getElementById("wrkflwUsrnamePopUp").value = document.getElementById('wrkflwUsername').innerHTML;
	document.getElementById("wrkflwUsrnamePopUp").style.border = '';
	document.getElementById("wrkflwPwdPopUp").value = document.getElementById('wrkflwPassword').innerHTML;
	document.getElementById("wrkflwPwdPopUp").style.border = '';
	if(document.getElementById('strDeleteFlag').innerHTML=='YES'){
		document.getElementById("itOpswrkflwDtlsDltChkBox").checked = true;
	}
	else{
		document.getElementById("itOpswrkflwDtlsDltChkBox").checked = false;
	}
	document.getElementById("itOpswrkflwDtlsDltDiv").style.display = 'block'; 
	$('#itOpsWrkflwDtlsAddEditPopUp').modal('show');
}
function fnItOpsValidateWrkflwDtlsPopUp(){
	 var varItOpsWrkflwDtlsValidationErrMsg = '';
	 var varWrkflwNamePopUp = document.getElementById('wrkflwNamePopUp').value;
	 var varWrkflwURLPopUp = document.getElementById('wrkflwURLPopUp').value;
	 var varWrkflwDeploymentIdPopUp = document.getElementById('wrkflwdeplymntIdPopUp').value;
	 var varWrkflwDefIdPopUp = document.getElementById('wrkflwDefIdPopUp').value;
	 var varWrkflwUsrnamePopUp = document.getElementById('wrkflwUsrnamePopUp').value;
	 var varWrkflwPwdPopUp = document.getElementById('wrkflwPwdPopUp').value;
	 
    if(varWrkflwNamePopUp == null || varWrkflwNamePopUp == "") {
    	varItOpsWrkflwDtlsValidationErrMsg = "Workflow Name";
    	setInvalidInputFieldBorderRed('wrkflwNamePopUp');
    }
	if(varWrkflwURLPopUp == null || varWrkflwURLPopUp == ""){
			if(varItOpsWrkflwDtlsValidationErrMsg.length > 0)
			{
				varItOpsWrkflwDtlsValidationErrMsg += ", ";
			}
			varItOpsWrkflwDtlsValidationErrMsg += "Workflow URL";
			setInvalidInputFieldBorderRed('wrkflwURLPopUp');
	}
	if(varWrkflwDeploymentIdPopUp == null || varWrkflwDeploymentIdPopUp == ""){
		if(varItOpsWrkflwDtlsValidationErrMsg.length > 0)
		{
			varItOpsWrkflwDtlsValidationErrMsg += ", ";
		}
		varItOpsWrkflwDtlsValidationErrMsg += "Workflow Deployment Id";
		setInvalidInputFieldBorderRed('wrkflwdeplymntIdPopUp');
	}
	if(varWrkflwDefIdPopUp == null || varWrkflwDefIdPopUp == ""){
		if(varItOpsWrkflwDtlsValidationErrMsg.length > 0)
		{
			varItOpsWrkflwDtlsValidationErrMsg += ", ";
		}
		varItOpsWrkflwDtlsValidationErrMsg += "Workflow Definition Id";
		setInvalidInputFieldBorderRed('wrkflwDefIdPopUp');
	}
	if(varWrkflwUsrnamePopUp == null || varWrkflwUsrnamePopUp == ""){
		if(varItOpsWrkflwDtlsValidationErrMsg.length > 0)
		{
			varItOpsWrkflwDtlsValidationErrMsg += ", ";
		}
		varItOpsWrkflwDtlsValidationErrMsg += "Workflow Username";
		setInvalidInputFieldBorderRed('wrkflwUsrnamePopUp');
	}
	if(varWrkflwPwdPopUp == null || varWrkflwPwdPopUp == ""){
		if(varItOpsWrkflwDtlsValidationErrMsg.length > 0)
		{
			varItOpsWrkflwDtlsValidationErrMsg += ", ";
		}
		varItOpsWrkflwDtlsValidationErrMsg += "Workflow Password";
		setInvalidInputFieldBorderRed('wrkflwPwdPopUp');
	}
	
	if(varItOpsWrkflwDtlsValidationErrMsg.length > 0)
	{
		varItOpsWrkflwDtlsValidationErrMsg += " are mandatory fields. ";
		//alert("varItOpsWrkflwDtlsValidationErrMsg"+varItOpsWrkflwDtlsValidationErrMsg);
	}
	if(varItOpsWrkflwDtlsValidationErrMsg == null || varItOpsWrkflwDtlsValidationErrMsg == ''){
		fnItOpsValWrkflwDtls();
	}else{
		//alert(varItOpsWrkflwDtlsValidationErrMsg+" Fields are Required:");
		fnShowItOpsValidationDialog(varItOpsWrkflwDtlsValidationErrMsg);
	}	
}

function fnItOpsValWrkflwDtls(){
	 //alert("inside fnItOpsGetWrkflwNameCount ");
	 var varGetWrkflwCountJsonObj = {};
	 varGetWrkflwCountJsonObj['wrkflwId'] = getValuesFromInputField("wrkflwIdPopUp");
	 varGetWrkflwCountJsonObj['wrkflwName'] = getValuesFromInputField("wrkflwNamePopUp");
	 //alert("name to controller"+varGetWrkflwCountJsonObj['wrkflwName']+"id"+ varGetWrkflwCountJsonObj['wrkflwId'] );
	 var strJSON = JSON.stringify(varGetWrkflwCountJsonObj);
	 fnCommonDoAjaxForGet("<%=request.getContextPath()%>/pages/itOpsValWrkflwDtls", strJSON,  "fnSucAfterValWrkflwDtls", "fnErrAfterValWrkflwDtls");
}
function fnSucAfterValWrkflwDtls(data){
	//alert("success"+data);
	if(data==0){
		fnItOpsSaveWrkflwDtls();
	}
	else{
		alert("Already workflow name exists");
	}
}
function fnErrAfterValWrkflwDtls(){
	alert("failure");
}
function fnItOpsSaveWrkflwDtls(){
	//alert("inside fnItOpsSaveSOPDTls");
	var varItOpsSaveWrkflwDtlsJsonObj = {};
	
	varItOpsSaveWrkflwDtlsJsonObj['wrkflwId'] = getValuesFromInputField("wrkflwIdPopUp");
	//alert("wrkflwId"+	varItOpsSaveWrkflwDtlsJsonObj['wrkflwId'] );
	
	varItOpsSaveWrkflwDtlsJsonObj['wrkflwName'] = getValuesFromInputField("wrkflwNamePopUp");
	//alert("wrkflwName"+	varItOpsSaveWrkflwDtlsJsonObj['wrkflwName'] );
	
	varItOpsSaveWrkflwDtlsJsonObj['wrkflwDesc'] = getValuesFromInputField("wrkflwDescPopUp");
	//alert("wrkflwDesc"+	varItOpsSaveWrkflwDtlsJsonObj['wrkflwDesc'] );
   
	varItOpsSaveWrkflwDtlsJsonObj['wrkflwUrl'] = getValuesFromInputField("wrkflwURLPopUp");
   // alert("wrkflwUrl"+	varItOpsSaveWrkflwDtlsJsonObj['wrkflwUrl'] );
   
    varItOpsSaveWrkflwDtlsJsonObj['wrkflwVersion'] = getValuesFromInputField("wrkflwVersionPopUp");
   // alert("wrkflwVersion"+	varItOpsSaveWrkflwDtlsJsonObj['wrkflwVersion'] );
    
    varItOpsSaveWrkflwDtlsJsonObj['wrkflwDeploymentId'] = getValuesFromInputField("wrkflwdeplymntIdPopUp");
   // alert("wrkflwDeploymentId"+	 varItOpsSaveWrkflwDtlsJsonObj['wrkflwDeploymentId'] );
   
    varItOpsSaveWrkflwDtlsJsonObj['wrkflwDecomisionDate'] = getValuesFromInputField("wrkflwDcmsnDatePopUp");
   // alert("wrkflwDecomisionDate"+	 varItOpsSaveWrkflwDtlsJsonObj['wrkflwDecomisionDate'] );
   
    varItOpsSaveWrkflwDtlsJsonObj['wrkflwListenQueue'] = getValuesFromInputField("wrkflwLstnQueuePopUp");
   // alert("wrkflwListenQueue"+	 varItOpsSaveWrkflwDtlsJsonObj['wrkflwListenQueue'] );
    
    varItOpsSaveWrkflwDtlsJsonObj['wrkflwDefinitionId'] = getValuesFromInputField("wrkflwDefIdPopUp");
  //  alert("wrkflwDefinitionId"+	 varItOpsSaveWrkflwDtlsJsonObj['wrkflwDefinitionId'] );
    
    varItOpsSaveWrkflwDtlsJsonObj['wrkflwUsername'] = getValuesFromInputField("wrkflwUsrnamePopUp");
   // alert("wrkflwUsername"+	 varItOpsSaveWrkflwDtlsJsonObj['wrkflwUsername'] );
    
    varItOpsSaveWrkflwDtlsJsonObj['wrkflwPassword'] = getValuesFromInputField("wrkflwPwdPopUp");
  //  alert("wrkflwPassword"+	 varItOpsSaveWrkflwDtlsJsonObj['wrkflwPassword'] );
    
	var checkboxvalue=document.getElementById("itOpswrkflwDtlsDltChkBox").checked;
   // alert("checkboxvalue"+checkboxvalue);
	if(checkboxvalue==true){
		varItOpsSaveWrkflwDtlsJsonObj['deleteFlag'] = 1;
	}
	else{
		varItOpsSaveWrkflwDtlsJsonObj['deleteFlag'] = 0;
	}
	//alert("deleteFlag"+	varItOpsSaveWrkflwDtlsJsonObj['deleteFlag'] );
	
	
	var strJSON = JSON.stringify(varItOpsSaveWrkflwDtlsJsonObj);
	//alert('strJSON is:'+strJSON+':');	
	if (confirm("Are you sure you want to save Workflow details") == true) {
		debugger;
		fnCommonDoAjaxForSave("<%=request.getContextPath()%>/pages/itOpsSaveWrkflwDtls", strJSON,  "fnItOpsFnAfterSaveWrkflwDtls", "fnItOpsFnErrAfterSaveWrkflwDtls"); 
	}
	else{
		$('#itOpsWrkflwDtlsAddEditPopUp').modal('hide');
	}
}
function fnItOpsFnAfterSaveWrkflwDtls(){
	//alert("success");
	$('#itOpsWrkflwDtlsAddEditPopUp').modal('hide');
	fnGetWrkflwDtls();
}
function fnItOpsFnErrAfterSaveWrkflwDtls(){
	alert("failure");
}
function fnItOpsAddWrkflwParam(){
	
	document.getElementById("wrkflwParamLnkIdPopUp").value = "";
	//document.getElementById("wrkflwIdParamPopUp").value = "";
	document.getElementById("paramNamePopUp").value = "";
	document.getElementById('paramNamePopUp').style.border = '';
	document.getElementById("paramCodePopUp").value = "";
	document.getElementById('paramCodePopUp').style.border = '';
	document.getElementById("paramValidatnPopUp").value = "";
	document.getElementById("paramOrderPopUp").value = "";
	document.getElementById("paramDefaultValPopUp").value = "";
	document.getElementById("paramTypePopUp").value = "";
	document.getElementById('paramTypePopUp').style.border = '';
	document.getElementById("paramTypeInWrkflwPopUp").value = "";
	document.getElementById("paramDescPopUp").value = "";
	document.getElementById("paramManditryChckBox").checked = false;
	document.getElementById("paramToBeStoredChckBox").checked = false;
	document.getElementById("paramToBeEncryptedChckBox").checked = false;
	document.getElementById("paramToBeShownChckBox").checked = false;
	document.getElementById("paramValToBeShownChckBox").checked = false;
	document.getElementById("paramCnsdrSOPPrmDtlChckBox").checked = false;
	document.getElementById("paramDltChckBox").checked = false;
	document.getElementById("itOpsWrkflwParamDtlsDltDiv").style.display = 'none';
	$('#itOpsWrkflwParamDtlsAddEditPopUp').modal('show');
}
function fnPopulateWrkflwParamDtlsInPopup(varItOpsWrkflwId,varItOpsWrkflwParamLnkId){
	//alert("inside fnPopulateWrkflwParamDtlsInPopup");
	var allWrkflwParamData = $('#itOpsWrkflwParam').DataTable().rows().data();
	for(var i=0;i<allWrkflwParamData.length;i++)
	{
		var tempWrkflwParamData = allWrkflwParamData [i];
		//alert("inside fnPopulateWrkflwParamDtlsInPopup fn., tempWrkflwParamData is:"+tempWrkflwParamData +':tempWrkflwParamData [wrkflwParamLnkId]:'+tempWrkflwParamData ['wrkflwParamLnkId']+':');
		var tempWrkflwParamLnkId = tempWrkflwParamData ['wrkflwParamLnkId'];
		if(tempWrkflwParamLnkId == varItOpsWrkflwParamLnkId)
		{
			
			$("#wrkflwParamLnkIdPopUp").val(varItOpsWrkflwParamLnkId);
			$("#wrkflwIdParamPopUp").val(varItOpsWrkflwId);
			//alert("workflow Id"+getValuesFromInputField("wrkflwIdParamPopUp"));
			$("#paramNamePopUp").val(tempWrkflwParamData ['paramName']);
			document.getElementById('paramNamePopUp').style.border = '';
			$("#paramCodePopUp").val(tempWrkflwParamData ['paramCode']);
			document.getElementById('paramCodePopUp').style.border = '';
			$("#paramValidatnPopUp").val(tempWrkflwParamData ['paramValidation']);
			$("#paramOrderPopUp").val(tempWrkflwParamData ['paramOrder']);
			$("#paramDefaultValPopUp").val(tempWrkflwParamData ['paramDefaultValue']);
			$("#paramTypePopUp").val(tempWrkflwParamData ['paramType']);
			document.getElementById('paramTypePopUp').style.border = '';
			$("#paramTypeInWrkflwPopUp").val(tempWrkflwParamData ['paramTypeInWorkflow']);
			$("#paramDescPopUp").val(tempWrkflwParamData ['paramDesc']);
			
			if(tempWrkflwParamData ['strParamMandatory']=='YES'){
				document.getElementById("paramManditryChckBox").checked = true;
			}
			else{
			document.getElementById("paramManditryChckBox").checked = false;
			}
			
			if(tempWrkflwParamData ['strParamToBeStored']=='YES'){
				document.getElementById("paramToBeStoredChckBox").checked = true;
			}
			else{
				document.getElementById("paramToBeStoredChckBox").checked = false;
			}
			
			if(tempWrkflwParamData ['strParamToBeEncrypted']=='YES'){
				document.getElementById("paramToBeEncryptedChckBox").checked = true;
			}							
			else{
				document.getElementById("paramToBeEncryptedChckBox").checked = false;
			}
			
			if(tempWrkflwParamData ['strParamToBeShown']=='YES'){
				document.getElementById("paramToBeShownChckBox").checked = true;
			}							
			else{
				document.getElementById("paramToBeShownChckBox").checked = false;
			}
			
			if(tempWrkflwParamData ['strParamValToBeShown']=='YES'){
				document.getElementById("paramValToBeShownChckBox").checked = true;
			}							
			else{
				document.getElementById("paramValToBeShownChckBox").checked = false;
			}
			
			if(tempWrkflwParamData ['strConsiderSopParamDtl']=='YES'){
				document.getElementById("paramCnsdrSOPPrmDtlChckBox").checked = true;
			}							
			else{
				document.getElementById("paramCnsdrSOPPrmDtlChckBox").checked = false;
			}
			
			if(tempWrkflwParamData ['strDeleteFlag']=='YES'){
				document.getElementById("paramDltChckBox").checked = true;
			}
			else{
			document.getElementById("paramDltChckBox").checked = false;
			}
			
			document.getElementById("itOpsWrkflwParamDtlsDltDiv").style.display = 'block';
			$('#itOpsWrkflwParamDtlsAddEditPopUp').modal('show');
			break;
		}
	
	} 
}

function fnItOpsValidateWrkflwParamDtlsPopUp(){
	 var varItOpsWrkflwParamDtlsValErrMsg = '';
	 var varWrkflwParamNamePopUp = document.getElementById('paramNamePopUp').value;
	 var varWrkflwParamCodePopUp = document.getElementById('paramCodePopUp').value;
	 var varWrkflwParamTypeIdPopUp = document.getElementById('paramTypePopUp').value;
	
	 
   if(varWrkflwParamNamePopUp == null || varWrkflwParamNamePopUp == "") {
	   varItOpsWrkflwParamDtlsValErrMsg = "Workflow param name";
   	setInvalidInputFieldBorderRed('paramNamePopUp');
   }
	if(varWrkflwParamCodePopUp == null || varWrkflwParamCodePopUp == ""){
			if(varItOpsWrkflwParamDtlsValErrMsg.length > 0)
			{
				varItOpsWrkflwParamDtlsValErrMsg += ", ";
			}
			varItOpsWrkflwParamDtlsValErrMsg += "Workflow param code";
			setInvalidInputFieldBorderRed('paramCodePopUp');
	}
	if(varWrkflwParamTypeIdPopUp == null || varWrkflwParamTypeIdPopUp == ""){
		if(varItOpsWrkflwParamDtlsValErrMsg.length > 0)
		{
			varItOpsWrkflwParamDtlsValErrMsg += ", ";
		}
		varItOpsWrkflwParamDtlsValErrMsg += "Workflow param type";
		setInvalidInputFieldBorderRed('paramTypePopUp');
	}
	if(varItOpsWrkflwParamDtlsValErrMsg.length > 0)
	{
		
		varItOpsWrkflwParamDtlsValErrMsg += " are mandatory fields. ";
		//alert("varItOpsWrkflwDtlsValidationErrMsg"+varItOpsWrkflwParamDtlsValErrMsg);
	}
	
	if(varItOpsWrkflwParamDtlsValErrMsg == null || varItOpsWrkflwParamDtlsValErrMsg == ''){
		fnItOpsValWrkflwParamDtls();
	}else{
		//alert(varItOpsWrkflwParamDtlsValErrMsg+" Fields are Required:");
		fnShowItOpsValidationDialog(varItOpsWrkflwParamDtlsValErrMsg);
	}	
}

function fnItOpsValWrkflwParamDtls(){
	 //alert("inside varItOpsWrkflwId ");
	 var varGetParamNameCountJsonObj = {};
	 varGetParamNameCountJsonObj['wrkflwParamLnkId'] = getValuesFromInputField("wrkflwParamLnkIdPopUp");
	 varGetParamNameCountJsonObj['wrkflwId'] = getValuesFromInputField("wrkflwIdParamPopUp");
	 varGetParamNameCountJsonObj['paramName'] = getValuesFromInputField("paramNamePopUp");
	 //alert("name to controller"+varGetParamNameCountJsonObj['paramName']+"wrkflwparamid"+ varGetParamNameCountJsonObj['wrkflwId']+"wrkflwParamLnkId"+varGetParamNameCountJsonObj['wrkflwParamLnkId']);
	 var strJSON = JSON.stringify(varGetParamNameCountJsonObj);
	 fnCommonDoAjaxForGet("<%=request.getContextPath()%>/pages/itOpsValWrkflwParamDtls", strJSON, "fnSucAfterValWrkflwParamDtls", "fnErrAfterValWrkflwParamDtls");
}
function fnSucAfterValWrkflwParamDtls(varWrkflwParamNameCount){
	//alert("success"+varWrkflwParamNameCount);
	if(varWrkflwParamNameCount==0){
		fnItOpsSaveWrkflwParamDtls();
	}
	else{
		alert("Name Already exists");
	}
}
function fnErrAfterValWrkflwParamDtls(){
	alert("failure");
}
function fnItOpsSaveWrkflwParamDtls(){
	//alert("inside fnItOpsSaveWrkflwParamDtls");
	var varItOpsSaveWrkflwParamDtlsJsonObj = {};
	varItOpsSaveWrkflwParamDtlsJsonObj['wrkflwId'] = getValuesFromInputField("wrkflwIdParamPopUp");
	varItOpsSaveWrkflwParamDtlsJsonObj['wrkflwParamLnkId'] = getValuesFromInputField("wrkflwParamLnkIdPopUp");
	varItOpsSaveWrkflwParamDtlsJsonObj['paramName'] = getValuesFromInputField("paramNamePopUp");
	varItOpsSaveWrkflwParamDtlsJsonObj['paramCode'] = getValuesFromInputField("paramCodePopUp");
	varItOpsSaveWrkflwParamDtlsJsonObj['paramValidation'] = getValuesFromInputField("paramValidatnPopUp");
	varItOpsSaveWrkflwParamDtlsJsonObj['paramOrder'] = getValuesFromInputField("paramOrderPopUp");
	varItOpsSaveWrkflwParamDtlsJsonObj['paramDefaultValue'] = getValuesFromInputField("paramDefaultValPopUp");
	varItOpsSaveWrkflwParamDtlsJsonObj['paramType'] = getValuesFromInputField("paramTypePopUp");
	varItOpsSaveWrkflwParamDtlsJsonObj['paramTypeInWrkflw'] = getValuesFromInputField("paramTypeInWrkflwPopUp");
	varItOpsSaveWrkflwParamDtlsJsonObj['paramDesc'] = getValuesFromInputField("paramDescPopUp");
	
	
	if(document.getElementById("paramManditryChckBox").checked==true){
		varItOpsSaveWrkflwParamDtlsJsonObj['paramMandatory'] = 1;
	}
	else{
		varItOpsSaveWrkflwParamDtlsJsonObj['paramMandatory'] = 0;
	}
	
	if(document.getElementById("paramToBeStoredChckBox").checked==true){
		varItOpsSaveWrkflwParamDtlsJsonObj['paramToBeStored'] = 1;
	}
	else{
		varItOpsSaveWrkflwParamDtlsJsonObj['paramToBeStored'] = 0;
	}
	
	if(document.getElementById("paramToBeEncryptedChckBox").checked==true){
		varItOpsSaveWrkflwParamDtlsJsonObj['paramToBeEncrypted'] = 1;
	}
	else{
		varItOpsSaveWrkflwParamDtlsJsonObj['paramToBeEncrypted'] = 0;
	}
	
	if(document.getElementById("paramToBeShownChckBox").checked==true){
		varItOpsSaveWrkflwParamDtlsJsonObj['paramToBeShown'] = 1;
	}
	else{
		varItOpsSaveWrkflwParamDtlsJsonObj['paramToBeShown'] = 0;
	}
	
	if(document.getElementById("paramValToBeShownChckBox").checked==true){
		varItOpsSaveWrkflwParamDtlsJsonObj['paramToBeShown'] = 1;
	}
	else{
		varItOpsSaveWrkflwParamDtlsJsonObj['paramToBeShown'] = 0;
	}
	
	if(document.getElementById("paramCnsdrSOPPrmDtlChckBox").checked==true){
		varItOpsSaveWrkflwParamDtlsJsonObj['considerSopParamDtl'] = 1;
	}
	else{
		varItOpsSaveWrkflwParamDtlsJsonObj['considerSopParamDtl'] = 0;
	}
	
	if(document.getElementById("paramDltChckBox").checked==true){
		varItOpsSaveWrkflwParamDtlsJsonObj['deleteFlag'] = 1;
	}
	else{
		varItOpsSaveWrkflwParamDtlsJsonObj['deleteFlag'] = 0;
	}
	var strJSON = JSON.stringify(varItOpsSaveWrkflwParamDtlsJsonObj);
	fnCommonDoAjaxForSave("<%=request.getContextPath()%>/pages/itOpsSaveWrkflwParamDtls", strJSON,  "fnItOpsFnAfterSaveWrkflwParamDtls", "fnItOpsFnErrSaveWrkflwParamDtls");
}
function fnItOpsFnAfterSaveWrkflwParamDtls(){
	//alert("sucess");
	$('#itOpsWrkflwParamDtlsAddEditPopUp').modal('hide');
	fnGetWrkflwDtls();
}
function fnItOpsFnErrSaveWrkflwParamDtls(){
	alert("failure");
} 
</script>
</head>
<body>

	<div class="tab-content padding-10">
		
		<!-- widget grid -->
		<section id="widget-grid" class="">
			<!-- row -->
			<div class="row" >
               
               <div class="row">
					<div class="col-md-8">
						<div class="form-group">
							<label for="category">Workflow Name</label>
				    		 <select  style="width: 180px;" id="wrkflwNameSelectId" name="wrkflwNameSelectId" onchange="javascript:getWrkflwDtlsByName(this.value)">
           					
           					 </select>
						</div>
					</div>
					
					<!--BUTTONS START -->
					<div class="pull-right" style="padding-right: 2%;">
						<a data-toggle="modal" onclick="fnItOpsWrkflwDtlsAddWrkflw()" class="btn btn-success txt-color-white pull-right  ">
							<i class="fa fa-circle-arrow-up fa-lg"></i>Add Workflow
						</a>   
						<br>
						<br>
				    </div>
				   <!--BUTTONS END -->
				   <!--BUTTONS START -->
					<div class="pull-right" style="padding-right: 2%;">
						<a data-toggle="modal" onclick="fnItOpsWrkflwDtlsEditWrkflw()" class="btn btn-success txt-color-white pull-right  ">
							<i class="fa fa-circle-arrow-up fa-lg"></i>Edit workflow
						</a>   
						<br>
						<br>
				    </div>
				   <!--BUTTONS END -->
				</div>
               		<article class="col-sm-12 col-md-12 col-lg-12">
				<!-- Widget ID (each widget will need unique ID)-->
							
							<div class="jarviswidget jarviswidget-color-blueDark" id="wid-id-2" data-widget-editbutton="false">
								
								<header>
								<!-- 	<span class="widget-icon"> <i class="fa fa-table"></i> </span> -->
									<h2>Workflow Details</h2>
								</header>
								<!-- widget div-->
								<div>
									<!-- widget edit box -->
									<div class="jarviswidget-editbox">
										<!-- This area used as dropdown edit box -->
									</div>
									<!-- end widget edit box -->
									<!-- widget content -->
									<div class="widget-body no-padding">
										<div class="table-responsive">
											<table id="itOpsWrkflwDtls" class="table table-hover">
                                       
                                                <tbody>
                                               
                                                   <tr>
                                                        <th>Workflow ID</th>
                                                        <td id='wrkflwId'></td>
                                                        <th>Description</th>
                                                          <td><textarea id="wrkflwDesc" rows="2" cols="50" disabled="disabled">
                                                        </textarea></td>
                                                    </tr>
                                                    
                                                
                                                    <tr>
                                                        <th>URL</th>
                                                        <td id='wrkflwUrl'></td>
                                                        <th>Version</th>
                                                        <td id='wrkflwVersion'></td>
                                                    </tr>
                                               		<tr>
                                                        <th>Deployment ID</th>
                                                        <td id='wrkflwDeploymentId'></td>
                                                        <th>Decommission Date</th>
                                                        <td id='strDecomisionDate'></td>
                                                    </tr>
                                                    <tr>
                                                   		  <th>Listen Queue</th>
                                                          <td id='wrkflwListenQueue'></td>
                                                          <th>Delete Flag?</th>
                                                          <td id='strDeleteFlag'></td>
                                                    </tr>
                                               		<tr>
                                                   		  <th>Created By</th>
                                                          <td id='createdByUserName'></td>
                                                          <th>Modified By</th>
                                                          <td id='modifiedByUserName'></td>
                                                    </tr>
                                                    <tr>
                                                   		  <th>Created Date</th>
                                                          <td id='strCreatedDate'></td>
                                                          <th>Modified Date</th>
                                                          <td id='strModifiedDate'></td>
                                                    </tr>
                                                   	<tr>
                                                   		  <th>Workflow Definition ID</th>
                                                          <td id='wrkflwDefinitionId'></td>
                                                          <th>Workflow Username</th>
                                                          <td id='wrkflwUsername'></td>
                                                    </tr>
                                                  
                                                    
                                                </tbody>
                                            </table>
                                          <input type="hidden" name="wrkflwPassword" id="wrkflwPassword" class="form-control"/>  
										</div>
										<!--  <div id='div1'> </div>  -->
									</div>
									<!-- end widget content -->

								</div>
								<!-- end widget div -->

							</div>
							<!-- end widget -->

				</article>
				

                </div>
                            <!-- end widget -->
		</section>
		<!--END SECTION WIDGET GRID -->
		
		<!-- widget grid -->
		<section id="widget-grid" class="">
			<!-- row -->
			<div class="row">
			
			
			<!--START ROW -->
							<div class="row">
								<!--BUTTONS START -->
								<div class="pull-right" style="padding-right: 2%;">
									<a data-toggle="modal" onclick="fnItOpsAddWrkflwParam()" class="btn btn-success txt-color-white pull-right  ">
										<i class="fa fa-circle-arrow-up fa-lg"></i>Add Workflow Param
									</a>   
								<br>
								<br>
							   </div>
							<!--BUTTONS END -->
						  </div>
						  <!--END ROW -->
			
				<!-- NEW WIDGET START -->
				<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
					<!-- Widget ID (each widget will need unique ID)-->
					<div class="jarviswidget jarviswidget-color-darken" id="itOpsDivWorkflowParam" data-widget-editbutton="false" data-widget-colorbutton="false">
					<!-- widget options:
							usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
			
							data-widget-colorbutton="false"
							data-widget-editbutton="false"
							data-widget-togglebutton="false"
							data-widget-deletebutton="false"
							data-widget-fullscreenbutton="false"
							data-widget-custombutton="false"
							data-widget-collapsed="true"
							data-widget-sortable="false"
			
							-->
						<header>
							<span class="widget-icon"> <i class="fa fa-table"></i> </span>
							<h2>Workflow Param Details<h2>
						</header>
						<!-- widget div-->
						<div>		
							<!-- widget edit box -->
							<div class="jarviswidget-editbox">
								<!-- This area used as dropdown edit box -->
							</div>
							<!-- end widget edit box -->
							<!-- widget content -->
							<div class="widget-body no-padding">
								<table id="itOpsWrkflwParam"
										class="table table-striped table-bordered table-hover"
										width="100%">
										<thead>
											<tr>
												<th> ID</th>
												<th> Param Name</th>
												<th> Param Code</th>
												<th> Param Validation</th>
												<th> Order</th>
												<th> Mandatory</th>
												<th> Default Value</th>
												<th> To be stored</th>
												<th> To be Encrypted</th>
												<th> To be shown</th>
												<th> Value to be shown</th>
												<th> Type in workflow</th>
												 <th> Created Date</th>
												<th> Modified Date</th> 
												<th> Consider sop param dtl</th>
												<th> Delete Flag</th>
												<th> Created By</th>
												<th> Modified By</th>
												<th> Param Desc</th>
												<th> Param Type</th>
												<th> Action</th>
											</tr>
										</thead>
		
										<tbody>
		
										</tbody>
									</table>
							</div>
							<!-- end widget content -->
						</div>
						<!-- end widget div -->
					</div>
					<!--END WIDGET ID -->
			</article>
				<!-- END ARTICLE-->	
			</div>
			<!-- END ROW-->	
		</section>
		<!--END SECTION WIDGET GRID -->
		
		<!-- widget grid -->
		<section id="widget-grid" class="">
			<!-- row -->
			<div class="row" >
               
               
               		<article class="col-sm-12 col-md-12 col-lg-12">
				<!-- Widget ID (each widget will need unique ID)-->
							
							<div class="jarviswidget jarviswidget-color-blueDark" id="wid-id-2" data-widget-editbutton="false">
								
								<header>
								<!-- 	<span class="widget-icon"> <i class="fa fa-table"></i> </span> -->
									<h2>Workflow Param Details contd..</h2>
								</header>
								<!-- widget div-->
								<div>
									<!-- widget edit box -->
									<div class="jarviswidget-editbox">
										<!-- This area used as dropdown edit box -->
									</div>
									<!-- end widget edit box -->
									<!-- widget content -->
									<div class="widget-body no-padding">
										<div class="table-responsive">
											<table id="itOpsWrkflwParamDtls" class="table table-hover">
                                       
                                                <tbody>
                                               			<tr>
                                                   		  	<th>Created By</th>
                                                         	<td id='createdByUsernameParam'></td>
                                                          	<th>Modified By</th>
                                                          	<td id='modifiedByUsernameParam'></td>
                                                    	</tr>
                                                    	<tr>
                                                   		 	 <th>Created Date</th>
                                                         	 <td id='strCreatedDateParam'></td>
                                                          	 <th>Modified Date</th>
                                                          	 <td id='strModifiedDateParam'></td>
                                                    	</tr>
                                                  		 <tr>
                                                  		 	 
                                                       	 	 <th>Description</th>
                                                        	 <td><textarea id="paramDesc" rows="2" cols="50" disabled="disabled">
                                                        	 </textarea></td>
                                                        	 <th></th>
                                                        	 <td></td>
                                                    	</tr>
                                                    	
                                                    
                                                </tbody>
                                            </table>
										</div>
										<!--  <div id='div1'> </div>  -->
									</div>
									<!-- end widget content -->

								</div>
								<!-- end widget div -->

							</div>
							<!-- end widget -->

				</article>
				

                </div>
                            <!-- end widget -->
		</section>
		<!--END SECTION WIDGET GRID -->
		
		
		<!-- Modal popup for  workflow -->
		<div class="modal fade" id="itOpsWrkflwDtlsAddEditPopUp" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
						<h4 class="modal-title">
							<b> Workflow Details</b>
						</h4>
					</div>
					<input type="hidden" name="wrkflwIdPopUp" id="wrkflwIdPopUp" class="form-control"/>
					
					<div class="modal-body">
						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									<label for="category"></label> Workflow Name <input type="text"
										name="wrkflwNamePopUp" id="wrkflwNamePopUp" class="form-control" required />
								</div>
							</div>
							<div class="col-md-6">
								<div class="form-group">
									<label for="category"></label> URL <input type="text"
										name="wrkflwURLPopUp" id="wrkflwURLPopUp" class="form-control" required />
								</div>
							</div>
							
						</div>
						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									<label for="category"></label> Deployment Id <input type="text"
										name="wrkflwdeplymntIdPopUp" id="wrkflwdeplymntIdPopUp" class="form-control" required />
								</div>
							</div>
							<div class="col-md-6">
								<div class="form-group">
									<label for="category"> Definition Id </label> <input type="text"
										name="wrkflwDefIdPopUp" id="wrkflwDefIdPopUp" class="form-control" required />
								</div>
							</div>
							
						</div>
						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									<label for="category"></label> Username <input type="text"
										name="wrkflwUsrnamePopUp" id="wrkflwUsrnamePopUp" class="form-control" required />
								</div>
							</div>
							
							<div class="col-md-6">
								<div class="form-group">
									<label for="category"> Password </label> <input type="text"
										name="wrkflwPwdPopUp" id="wrkflwPwdPopUp" class="form-control" required />
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									<label for="category"> Description </label> <input type="text"
										name="wrkflwDescPopUp" id="wrkflwDescPopUp" class="form-control" required />
								</div>
							</div>
							
							<div class="col-md-6">
								<div class="form-group">
									<label for="category"> Version </label> <input type="text"
										name="wrkflwVersionPopUp" id="wrkflwVersionPopUp" class="form-control" required />
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									<label for="category"></label> Listen Queue <input type="text"
										name="wrkflwLstnQueuePopUp" id="wrkflwLstnQueuePopUp" class="form-control" required />
								</div>
							</div>
							<div class="col-md-6">
								<div class="form-group">
									<label for="category"> Decomission Date </label> <input type="text"
										name="wrkflwDcmsnDatePopUp" id="wrkflwDcmsnDatePopUp" class="form-control" required />
								</div>
							</div>
							
						</div>
						
						<div class="row">
							<div class="col-md-6" id="itOpswrkflwDtlsDltDiv"  style="display:none" >
								<div class="inline-group">
									<label class="checkbox">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
									<input type="checkbox" id="itOpswrkflwDtlsDltChkBox" name="itOpswrkflwDtlsDltChkBox">
									<i></i>Delete ?</label>
									</div>
								</div>
                        </div>
              

						<div class="modal-footer">
							<footer>
								<button type="button" class="btn btn-primary" onclick="javascript:fnItOpsValidateWrkflwDtlsPopUp();">Save</button>
								<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
							</footer>
						</div>
							<!-- </form>	 -->
						</div>
					<!-- -/.modal-body -->
				</div>
				<!-- /.modal-content -->
			</div>
			<!-- /.modal-dialog -->

		</div>
		<!-- /.modal -->
	<!-- modal popup end workflow -->
		
	<!-- Modal popup for  workflow paramS-->
		<div class="modal fade" id="itOpsWrkflwParamDtlsAddEditPopUp" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
						<h4 class="modal-title">
							<b> Workflow Param Details</b>
						</h4>
					</div>
					<input type="hidden" name="wrkflwParamLnkIdPopUp" id="wrkflwParamLnkIdPopUp" class="form-control"/>
					<input type="hidden" name="wrkflwIdParamPopUp" id="wrkflwIdParamPopUp" class="form-control"/>
					
					<div class="modal-body">
						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									<label for="category"></label> Param Name <input type="text"
										name="paramNamePopUp" id="paramNamePopUp" class="form-control" required />
								</div>
							</div>
							<div class="col-md-6">
								<div class="form-group">
									<label for="category"></label> Param Code <input type="text"
										name="paramCodePopUp" id="paramCodePopUp" class="form-control" required />
								</div>
							</div>
							
						</div>
						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									<label for="category"></label> Validation <input type="text"
										name="paramValidatnPopUp" id="paramValidatnPopUp" class="form-control" required />
								</div>
							</div>
							<div class="col-md-6">
								<div class="form-group">
									<label for="category"> Order </label> <input type="text"
										name="paramOrderPopUp" id="paramOrderPopUp" class="form-control" required />
								</div>
							</div>
							
						</div>
						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									<label for="category"></label> Default Value <input type="text"
										name="paramDefaultValPopUp" id="paramDefaultValPopUp" class="form-control" required />
								</div>
							</div>
							<div class="col-md-6">
								<div class="form-group">
									<label for="category"></label> Description <input type="text"
										name="paramDescPopUp" id="paramDescPopUp" class="form-control" required />
								</div>
							</div>
							
						</div>
						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									<label for="category"> Param Type </label> <input type="text"
										name="paramTypePopUp" id="paramTypePopUp" class="form-control" required />
								</div>
							</div>
							
							<div class="col-md-6">
								<div class="form-group">
									<label for="category"> Type in workflow </label> <input type="text"
										name="paramTypeInWrkflwPopUp" id="paramTypeInWrkflwPopUp" class="form-control" required />
								</div>
							</div>
						</div>
						
						
						<div class="row">
							<div class="col-md-6" >
								<div class="inline-group">
									<label class="checkbox">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
									<input type="checkbox" id="paramManditryChckBox" name="paramManditryChckBox">
									<i></i>Mandatory ?</label>
									</div>
							</div>
							<div class="col-md-6">
								<div class="inline-group">
									<label class="checkbox">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
									<input type="checkbox" id="paramToBeStoredChckBox" name="paramToBeStoredChckBox">
									<i></i>To be Stored ?</label>
									</div>
							</div>
                        </div>
              			<div class="row">
							<div class="col-md-6" >
								<div class="inline-group">
									<label class="checkbox">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
									<input type="checkbox" id="paramToBeEncryptedChckBox" name="paramToBeEncryptedChckBox">
									<i></i>To be encrypted ?</label>
									</div>
							</div>
							<div class="col-md-6" >
								<div class="inline-group">
									<label class="checkbox">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
									<input type="checkbox" id="paramToBeShownChckBox" name="paramToBeShownChckBox">
									<i></i>To be shown ?</label>
									</div>
							</div>
                        </div>
                        <div class="row">
							<div class="col-md-6" >
								<div class="inline-group">
									<label class="checkbox">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
									<input type="checkbox" id="paramValToBeShownChckBox" name="paramValToBeShownChckBox">
									<i></i>Value to be shown ?</label>
									</div>
							</div>
							<div class="col-md-6" >
								<div class="inline-group">
									<label class="checkbox">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
									<input type="checkbox" id="paramCnsdrSOPPrmDtlChckBox" name="paramCnsdrSOPPrmDtlChckBox">
									<i></i>Consider SOP Param details ?</label>
									</div>
							</div>
						</div>
                        <div class="row">
							<div class="col-md-6" id="itOpsWrkflwParamDtlsDltDiv"  style="display:none" >
								<div class="inline-group">
									<label class="checkbox">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
									<input type="checkbox" id="paramDltChckBox" name="paramDltChckBox">
									<i></i>Delete ?</label>
									</div>
							</div>
                        </div>

						<div class="modal-footer">
							<footer>
								<button type="button" class="btn btn-primary" onclick="javascript:fnItOpsValidateWrkflwParamDtlsPopUp();">Save</button>
								<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
							</footer>
						</div>
							<!-- </form>	 -->
						</div>
					<!-- -/.modal-body -->
				</div>
				<!-- /.modal-content -->
			</div>
			<!-- /.modal-dialog -->

		</div>
		<!-- /.modal -->
	<!-- modal popup end workflow -->	
	</div>
</body>

</html>